<?php
/**
 * AktuellesAngebotApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Leifos\VedaConnector\GeneratedOpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * VEDA Bildungsmanager API
 *
 * Dokumentation der REST-Schnittstellen des VEDA Bildungsmanagers. Die Dokumentation zu speziellen Versionen sind unter den jeweiligen Pfaden abrufbar, z.B.: ./api/docs/v1 für Version 1, /api/docs/v2 für Version 2.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Leifos\VedaConnector\GeneratedOpenApi\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Leifos\VedaConnector\GeneratedOpenApi\ApiException;
use Leifos\VedaConnector\GeneratedOpenApi\Configuration;
use Leifos\VedaConnector\GeneratedOpenApi\FormDataProcessor;
use Leifos\VedaConnector\GeneratedOpenApi\HeaderSelector;
use Leifos\VedaConnector\GeneratedOpenApi\ObjectSerializer;

/**
 * AktuellesAngebotApi Class Doc Comment
 *
 * @category Class
 * @package  Leifos\VedaConnector\GeneratedOpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AktuellesAngebotApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getAktuellesAngebot' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getAktuellesAngebot
     *
     * Ruft das aktuelle Angebot ab
     *
     * @param  string $teilnehmergruppekuerzel Pflicht Parameter, um zu steuern, für welche Teilnehmergruppe das aktuelle Angebot abgerufen werden sollen. Für die angegebene Teilnehmergruppe, werden alle Veranstaltungstermine und Veranstaltungsterminreihen im Rahmen des aktuellen Angebotes die für diese Teilnehmergruppe publiziert sind zurückgegeben. (required)
     * @param  string|null $plz Optionaler Parameter, der es erlaubt das Ergebnis auf einen PLZ-Bereich einzuschränken. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAktuellesAngebot'] to see the possible values for this operation
     *
     * @throws \Leifos\VedaConnector\GeneratedOpenApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Leifos\VedaConnector\GeneratedOpenApi\Model\AktuellesAngebot
     */
    public function getAktuellesAngebot($teilnehmergruppekuerzel, $plz = null, string $contentType = self::contentTypes['getAktuellesAngebot'][0])
    {
        list($response) = $this->getAktuellesAngebotWithHttpInfo($teilnehmergruppekuerzel, $plz, $contentType);
        return $response;
    }

    /**
     * Operation getAktuellesAngebotWithHttpInfo
     *
     * Ruft das aktuelle Angebot ab
     *
     * @param  string $teilnehmergruppekuerzel Pflicht Parameter, um zu steuern, für welche Teilnehmergruppe das aktuelle Angebot abgerufen werden sollen. Für die angegebene Teilnehmergruppe, werden alle Veranstaltungstermine und Veranstaltungsterminreihen im Rahmen des aktuellen Angebotes die für diese Teilnehmergruppe publiziert sind zurückgegeben. (required)
     * @param  string|null $plz Optionaler Parameter, der es erlaubt das Ergebnis auf einen PLZ-Bereich einzuschränken. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAktuellesAngebot'] to see the possible values for this operation
     *
     * @throws \Leifos\VedaConnector\GeneratedOpenApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Leifos\VedaConnector\GeneratedOpenApi\Model\AktuellesAngebot, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAktuellesAngebotWithHttpInfo($teilnehmergruppekuerzel, $plz = null, string $contentType = self::contentTypes['getAktuellesAngebot'][0])
    {
        $request = $this->getAktuellesAngebotRequest($teilnehmergruppekuerzel, $plz, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Leifos\VedaConnector\GeneratedOpenApi\Model\AktuellesAngebot',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Leifos\VedaConnector\GeneratedOpenApi\Model\AktuellesAngebot',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Leifos\VedaConnector\GeneratedOpenApi\Model\AktuellesAngebot',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getAktuellesAngebotAsync
     *
     * Ruft das aktuelle Angebot ab
     *
     * @param  string $teilnehmergruppekuerzel Pflicht Parameter, um zu steuern, für welche Teilnehmergruppe das aktuelle Angebot abgerufen werden sollen. Für die angegebene Teilnehmergruppe, werden alle Veranstaltungstermine und Veranstaltungsterminreihen im Rahmen des aktuellen Angebotes die für diese Teilnehmergruppe publiziert sind zurückgegeben. (required)
     * @param  string|null $plz Optionaler Parameter, der es erlaubt das Ergebnis auf einen PLZ-Bereich einzuschränken. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAktuellesAngebot'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAktuellesAngebotAsync($teilnehmergruppekuerzel, $plz = null, string $contentType = self::contentTypes['getAktuellesAngebot'][0])
    {
        return $this->getAktuellesAngebotAsyncWithHttpInfo($teilnehmergruppekuerzel, $plz, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAktuellesAngebotAsyncWithHttpInfo
     *
     * Ruft das aktuelle Angebot ab
     *
     * @param  string $teilnehmergruppekuerzel Pflicht Parameter, um zu steuern, für welche Teilnehmergruppe das aktuelle Angebot abgerufen werden sollen. Für die angegebene Teilnehmergruppe, werden alle Veranstaltungstermine und Veranstaltungsterminreihen im Rahmen des aktuellen Angebotes die für diese Teilnehmergruppe publiziert sind zurückgegeben. (required)
     * @param  string|null $plz Optionaler Parameter, der es erlaubt das Ergebnis auf einen PLZ-Bereich einzuschränken. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAktuellesAngebot'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAktuellesAngebotAsyncWithHttpInfo($teilnehmergruppekuerzel, $plz = null, string $contentType = self::contentTypes['getAktuellesAngebot'][0])
    {
        $returnType = '\Leifos\VedaConnector\GeneratedOpenApi\Model\AktuellesAngebot';
        $request = $this->getAktuellesAngebotRequest($teilnehmergruppekuerzel, $plz, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAktuellesAngebot'
     *
     * @param  string $teilnehmergruppekuerzel Pflicht Parameter, um zu steuern, für welche Teilnehmergruppe das aktuelle Angebot abgerufen werden sollen. Für die angegebene Teilnehmergruppe, werden alle Veranstaltungstermine und Veranstaltungsterminreihen im Rahmen des aktuellen Angebotes die für diese Teilnehmergruppe publiziert sind zurückgegeben. (required)
     * @param  string|null $plz Optionaler Parameter, der es erlaubt das Ergebnis auf einen PLZ-Bereich einzuschränken. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAktuellesAngebot'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getAktuellesAngebotRequest($teilnehmergruppekuerzel, $plz = null, string $contentType = self::contentTypes['getAktuellesAngebot'][0])
    {

        // verify the required parameter 'teilnehmergruppekuerzel' is set
        if ($teilnehmergruppekuerzel === null || (is_array($teilnehmergruppekuerzel) && count($teilnehmergruppekuerzel) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $teilnehmergruppekuerzel when calling getAktuellesAngebot'
            );
        }



        $resourcePath = '/v2/aktuellesangebot';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $teilnehmergruppekuerzel,
            'teilnehmergruppekuerzel', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $plz,
            'plz', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['*/*', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-jwp-apiaccesstoken');
        if ($apiKey !== null) {
            $headers['x-jwp-apiaccesstoken'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
