<?php
/**
 * AusbildungszugabschnitteApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Leifos\VedaConnector\GeneratedOpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * VEDA Bildungsmanager API
 *
 * Dokumentation der REST-Schnittstellen des VEDA Bildungsmanagers. Die Dokumentation zu speziellen Versionen sind unter den jeweiligen Pfaden abrufbar, z.B.: ./api/docs/v1 für Version 1, /api/docs/v2 für Version 2.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Leifos\VedaConnector\GeneratedOpenApi\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Leifos\VedaConnector\GeneratedOpenApi\ApiException;
use Leifos\VedaConnector\GeneratedOpenApi\Configuration;
use Leifos\VedaConnector\GeneratedOpenApi\FormDataProcessor;
use Leifos\VedaConnector\GeneratedOpenApi\HeaderSelector;
use Leifos\VedaConnector\GeneratedOpenApi\ObjectSerializer;

/**
 * AusbildungszugabschnitteApi Class Doc Comment
 *
 * @category Class
 * @package  Leifos\VedaConnector\GeneratedOpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AusbildungszugabschnitteApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'meldeLernerfolg' => [
            'application/json',
        ],
        'meldePraktikumsberichtEingegangen' => [
            'application/json',
        ],
        'meldePraktikumsberichtKorrigiert' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation meldeLernerfolg
     *
     * Ermöglicht es, den Lernerfolg eines Ausbildungszugabschnitts für den angegebenen Teilnehmer zu melden
     *
     * @param  string $ausbildungszugabschnitt_id ID des Ausbildungszugabschnitts (required)
     * @param  string $teilnehmer_id ID des Teilnehmers (required)
     * @param  \Leifos\VedaConnector\GeneratedOpenApi\Model\MeldeLernerfolgApiDto $melde_lernerfolg_api_dto melde_lernerfolg_api_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['meldeLernerfolg'] to see the possible values for this operation
     *
     * @throws \Leifos\VedaConnector\GeneratedOpenApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function meldeLernerfolg($ausbildungszugabschnitt_id, $teilnehmer_id, $melde_lernerfolg_api_dto, string $contentType = self::contentTypes['meldeLernerfolg'][0])
    {
        $this->meldeLernerfolgWithHttpInfo($ausbildungszugabschnitt_id, $teilnehmer_id, $melde_lernerfolg_api_dto, $contentType);
    }

    /**
     * Operation meldeLernerfolgWithHttpInfo
     *
     * Ermöglicht es, den Lernerfolg eines Ausbildungszugabschnitts für den angegebenen Teilnehmer zu melden
     *
     * @param  string $ausbildungszugabschnitt_id ID des Ausbildungszugabschnitts (required)
     * @param  string $teilnehmer_id ID des Teilnehmers (required)
     * @param  \Leifos\VedaConnector\GeneratedOpenApi\Model\MeldeLernerfolgApiDto $melde_lernerfolg_api_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['meldeLernerfolg'] to see the possible values for this operation
     *
     * @throws \Leifos\VedaConnector\GeneratedOpenApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function meldeLernerfolgWithHttpInfo($ausbildungszugabschnitt_id, $teilnehmer_id, $melde_lernerfolg_api_dto, string $contentType = self::contentTypes['meldeLernerfolg'][0])
    {
        $request = $this->meldeLernerfolgRequest($ausbildungszugabschnitt_id, $teilnehmer_id, $melde_lernerfolg_api_dto, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation meldeLernerfolgAsync
     *
     * Ermöglicht es, den Lernerfolg eines Ausbildungszugabschnitts für den angegebenen Teilnehmer zu melden
     *
     * @param  string $ausbildungszugabschnitt_id ID des Ausbildungszugabschnitts (required)
     * @param  string $teilnehmer_id ID des Teilnehmers (required)
     * @param  \Leifos\VedaConnector\GeneratedOpenApi\Model\MeldeLernerfolgApiDto $melde_lernerfolg_api_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['meldeLernerfolg'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function meldeLernerfolgAsync($ausbildungszugabschnitt_id, $teilnehmer_id, $melde_lernerfolg_api_dto, string $contentType = self::contentTypes['meldeLernerfolg'][0])
    {
        return $this->meldeLernerfolgAsyncWithHttpInfo($ausbildungszugabschnitt_id, $teilnehmer_id, $melde_lernerfolg_api_dto, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation meldeLernerfolgAsyncWithHttpInfo
     *
     * Ermöglicht es, den Lernerfolg eines Ausbildungszugabschnitts für den angegebenen Teilnehmer zu melden
     *
     * @param  string $ausbildungszugabschnitt_id ID des Ausbildungszugabschnitts (required)
     * @param  string $teilnehmer_id ID des Teilnehmers (required)
     * @param  \Leifos\VedaConnector\GeneratedOpenApi\Model\MeldeLernerfolgApiDto $melde_lernerfolg_api_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['meldeLernerfolg'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function meldeLernerfolgAsyncWithHttpInfo($ausbildungszugabschnitt_id, $teilnehmer_id, $melde_lernerfolg_api_dto, string $contentType = self::contentTypes['meldeLernerfolg'][0])
    {
        $returnType = '';
        $request = $this->meldeLernerfolgRequest($ausbildungszugabschnitt_id, $teilnehmer_id, $melde_lernerfolg_api_dto, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'meldeLernerfolg'
     *
     * @param  string $ausbildungszugabschnitt_id ID des Ausbildungszugabschnitts (required)
     * @param  string $teilnehmer_id ID des Teilnehmers (required)
     * @param  \Leifos\VedaConnector\GeneratedOpenApi\Model\MeldeLernerfolgApiDto $melde_lernerfolg_api_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['meldeLernerfolg'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function meldeLernerfolgRequest($ausbildungszugabschnitt_id, $teilnehmer_id, $melde_lernerfolg_api_dto, string $contentType = self::contentTypes['meldeLernerfolg'][0])
    {

        // verify the required parameter 'ausbildungszugabschnitt_id' is set
        if ($ausbildungszugabschnitt_id === null || (is_array($ausbildungszugabschnitt_id) && count($ausbildungszugabschnitt_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ausbildungszugabschnitt_id when calling meldeLernerfolg'
            );
        }

        // verify the required parameter 'teilnehmer_id' is set
        if ($teilnehmer_id === null || (is_array($teilnehmer_id) && count($teilnehmer_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $teilnehmer_id when calling meldeLernerfolg'
            );
        }

        // verify the required parameter 'melde_lernerfolg_api_dto' is set
        if ($melde_lernerfolg_api_dto === null || (is_array($melde_lernerfolg_api_dto) && count($melde_lernerfolg_api_dto) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $melde_lernerfolg_api_dto when calling meldeLernerfolg'
            );
        }


        $resourcePath = '/v2/ausbildungszugabschnitte/{ausbildungszugabschnittId}/teilnehmer/{teilnehmerId}/meldelernerfolg';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($ausbildungszugabschnitt_id !== null) {
            $resourcePath = str_replace(
                '{ausbildungszugabschnittId}',
                ObjectSerializer::toPathValue($ausbildungszugabschnitt_id),
                $resourcePath
            );
        }
        // path params
        if ($teilnehmer_id !== null) {
            $resourcePath = str_replace(
                '{teilnehmerId}',
                ObjectSerializer::toPathValue($teilnehmer_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($melde_lernerfolg_api_dto)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($melde_lernerfolg_api_dto));
            } else {
                $httpBody = $melde_lernerfolg_api_dto;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-jwp-apiaccesstoken');
        if ($apiKey !== null) {
            $headers['x-jwp-apiaccesstoken'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation meldePraktikumsberichtEingegangen
     *
     * Ermöglicht es, den Eingang eines Praktikumsberichts für den angegebenen Teilnehmer zu melden
     *
     * @param  string $ausbildungszugabschnitt_id ID des Ausbildungszugabschnitts (required)
     * @param  string $teilnehmer_id ID des Teilnehmers (required)
     * @param  \Leifos\VedaConnector\GeneratedOpenApi\Model\PraktikumsberichtEingegangenApiDto $praktikumsbericht_eingegangen_api_dto praktikumsbericht_eingegangen_api_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['meldePraktikumsberichtEingegangen'] to see the possible values for this operation
     *
     * @throws \Leifos\VedaConnector\GeneratedOpenApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function meldePraktikumsberichtEingegangen($ausbildungszugabschnitt_id, $teilnehmer_id, $praktikumsbericht_eingegangen_api_dto, string $contentType = self::contentTypes['meldePraktikumsberichtEingegangen'][0])
    {
        $this->meldePraktikumsberichtEingegangenWithHttpInfo($ausbildungszugabschnitt_id, $teilnehmer_id, $praktikumsbericht_eingegangen_api_dto, $contentType);
    }

    /**
     * Operation meldePraktikumsberichtEingegangenWithHttpInfo
     *
     * Ermöglicht es, den Eingang eines Praktikumsberichts für den angegebenen Teilnehmer zu melden
     *
     * @param  string $ausbildungszugabschnitt_id ID des Ausbildungszugabschnitts (required)
     * @param  string $teilnehmer_id ID des Teilnehmers (required)
     * @param  \Leifos\VedaConnector\GeneratedOpenApi\Model\PraktikumsberichtEingegangenApiDto $praktikumsbericht_eingegangen_api_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['meldePraktikumsberichtEingegangen'] to see the possible values for this operation
     *
     * @throws \Leifos\VedaConnector\GeneratedOpenApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function meldePraktikumsberichtEingegangenWithHttpInfo($ausbildungszugabschnitt_id, $teilnehmer_id, $praktikumsbericht_eingegangen_api_dto, string $contentType = self::contentTypes['meldePraktikumsberichtEingegangen'][0])
    {
        $request = $this->meldePraktikumsberichtEingegangenRequest($ausbildungszugabschnitt_id, $teilnehmer_id, $praktikumsbericht_eingegangen_api_dto, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation meldePraktikumsberichtEingegangenAsync
     *
     * Ermöglicht es, den Eingang eines Praktikumsberichts für den angegebenen Teilnehmer zu melden
     *
     * @param  string $ausbildungszugabschnitt_id ID des Ausbildungszugabschnitts (required)
     * @param  string $teilnehmer_id ID des Teilnehmers (required)
     * @param  \Leifos\VedaConnector\GeneratedOpenApi\Model\PraktikumsberichtEingegangenApiDto $praktikumsbericht_eingegangen_api_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['meldePraktikumsberichtEingegangen'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function meldePraktikumsberichtEingegangenAsync($ausbildungszugabschnitt_id, $teilnehmer_id, $praktikumsbericht_eingegangen_api_dto, string $contentType = self::contentTypes['meldePraktikumsberichtEingegangen'][0])
    {
        return $this->meldePraktikumsberichtEingegangenAsyncWithHttpInfo($ausbildungszugabschnitt_id, $teilnehmer_id, $praktikumsbericht_eingegangen_api_dto, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation meldePraktikumsberichtEingegangenAsyncWithHttpInfo
     *
     * Ermöglicht es, den Eingang eines Praktikumsberichts für den angegebenen Teilnehmer zu melden
     *
     * @param  string $ausbildungszugabschnitt_id ID des Ausbildungszugabschnitts (required)
     * @param  string $teilnehmer_id ID des Teilnehmers (required)
     * @param  \Leifos\VedaConnector\GeneratedOpenApi\Model\PraktikumsberichtEingegangenApiDto $praktikumsbericht_eingegangen_api_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['meldePraktikumsberichtEingegangen'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function meldePraktikumsberichtEingegangenAsyncWithHttpInfo($ausbildungszugabschnitt_id, $teilnehmer_id, $praktikumsbericht_eingegangen_api_dto, string $contentType = self::contentTypes['meldePraktikumsberichtEingegangen'][0])
    {
        $returnType = '';
        $request = $this->meldePraktikumsberichtEingegangenRequest($ausbildungszugabschnitt_id, $teilnehmer_id, $praktikumsbericht_eingegangen_api_dto, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'meldePraktikumsberichtEingegangen'
     *
     * @param  string $ausbildungszugabschnitt_id ID des Ausbildungszugabschnitts (required)
     * @param  string $teilnehmer_id ID des Teilnehmers (required)
     * @param  \Leifos\VedaConnector\GeneratedOpenApi\Model\PraktikumsberichtEingegangenApiDto $praktikumsbericht_eingegangen_api_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['meldePraktikumsberichtEingegangen'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function meldePraktikumsberichtEingegangenRequest($ausbildungszugabschnitt_id, $teilnehmer_id, $praktikumsbericht_eingegangen_api_dto, string $contentType = self::contentTypes['meldePraktikumsberichtEingegangen'][0])
    {

        // verify the required parameter 'ausbildungszugabschnitt_id' is set
        if ($ausbildungszugabschnitt_id === null || (is_array($ausbildungszugabschnitt_id) && count($ausbildungszugabschnitt_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ausbildungszugabschnitt_id when calling meldePraktikumsberichtEingegangen'
            );
        }

        // verify the required parameter 'teilnehmer_id' is set
        if ($teilnehmer_id === null || (is_array($teilnehmer_id) && count($teilnehmer_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $teilnehmer_id when calling meldePraktikumsberichtEingegangen'
            );
        }

        // verify the required parameter 'praktikumsbericht_eingegangen_api_dto' is set
        if ($praktikumsbericht_eingegangen_api_dto === null || (is_array($praktikumsbericht_eingegangen_api_dto) && count($praktikumsbericht_eingegangen_api_dto) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $praktikumsbericht_eingegangen_api_dto when calling meldePraktikumsberichtEingegangen'
            );
        }


        $resourcePath = '/v2/ausbildungszugabschnitte/{ausbildungszugabschnittId}/teilnehmer/{teilnehmerId}/meldepraktikumsberichteingegangen';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($ausbildungszugabschnitt_id !== null) {
            $resourcePath = str_replace(
                '{ausbildungszugabschnittId}',
                ObjectSerializer::toPathValue($ausbildungszugabschnitt_id),
                $resourcePath
            );
        }
        // path params
        if ($teilnehmer_id !== null) {
            $resourcePath = str_replace(
                '{teilnehmerId}',
                ObjectSerializer::toPathValue($teilnehmer_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($praktikumsbericht_eingegangen_api_dto)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($praktikumsbericht_eingegangen_api_dto));
            } else {
                $httpBody = $praktikumsbericht_eingegangen_api_dto;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-jwp-apiaccesstoken');
        if ($apiKey !== null) {
            $headers['x-jwp-apiaccesstoken'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation meldePraktikumsberichtKorrigiert
     *
     * Ermöglicht es, den korrigierten Praktikumsbericht für den angegebenen Teilnehmer zu melden
     *
     * @param  string $ausbildungszugabschnitt_id ID des Ausbildungszugabschnitts (required)
     * @param  string $teilnehmer_id ID des Teilnehmers (required)
     * @param  \Leifos\VedaConnector\GeneratedOpenApi\Model\PraktikumsberichtKorrigiertApiDto $praktikumsbericht_korrigiert_api_dto praktikumsbericht_korrigiert_api_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['meldePraktikumsberichtKorrigiert'] to see the possible values for this operation
     *
     * @throws \Leifos\VedaConnector\GeneratedOpenApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function meldePraktikumsberichtKorrigiert($ausbildungszugabschnitt_id, $teilnehmer_id, $praktikumsbericht_korrigiert_api_dto, string $contentType = self::contentTypes['meldePraktikumsberichtKorrigiert'][0])
    {
        $this->meldePraktikumsberichtKorrigiertWithHttpInfo($ausbildungszugabschnitt_id, $teilnehmer_id, $praktikumsbericht_korrigiert_api_dto, $contentType);
    }

    /**
     * Operation meldePraktikumsberichtKorrigiertWithHttpInfo
     *
     * Ermöglicht es, den korrigierten Praktikumsbericht für den angegebenen Teilnehmer zu melden
     *
     * @param  string $ausbildungszugabschnitt_id ID des Ausbildungszugabschnitts (required)
     * @param  string $teilnehmer_id ID des Teilnehmers (required)
     * @param  \Leifos\VedaConnector\GeneratedOpenApi\Model\PraktikumsberichtKorrigiertApiDto $praktikumsbericht_korrigiert_api_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['meldePraktikumsberichtKorrigiert'] to see the possible values for this operation
     *
     * @throws \Leifos\VedaConnector\GeneratedOpenApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function meldePraktikumsberichtKorrigiertWithHttpInfo($ausbildungszugabschnitt_id, $teilnehmer_id, $praktikumsbericht_korrigiert_api_dto, string $contentType = self::contentTypes['meldePraktikumsberichtKorrigiert'][0])
    {
        $request = $this->meldePraktikumsberichtKorrigiertRequest($ausbildungszugabschnitt_id, $teilnehmer_id, $praktikumsbericht_korrigiert_api_dto, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation meldePraktikumsberichtKorrigiertAsync
     *
     * Ermöglicht es, den korrigierten Praktikumsbericht für den angegebenen Teilnehmer zu melden
     *
     * @param  string $ausbildungszugabschnitt_id ID des Ausbildungszugabschnitts (required)
     * @param  string $teilnehmer_id ID des Teilnehmers (required)
     * @param  \Leifos\VedaConnector\GeneratedOpenApi\Model\PraktikumsberichtKorrigiertApiDto $praktikumsbericht_korrigiert_api_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['meldePraktikumsberichtKorrigiert'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function meldePraktikumsberichtKorrigiertAsync($ausbildungszugabschnitt_id, $teilnehmer_id, $praktikumsbericht_korrigiert_api_dto, string $contentType = self::contentTypes['meldePraktikumsberichtKorrigiert'][0])
    {
        return $this->meldePraktikumsberichtKorrigiertAsyncWithHttpInfo($ausbildungszugabschnitt_id, $teilnehmer_id, $praktikumsbericht_korrigiert_api_dto, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation meldePraktikumsberichtKorrigiertAsyncWithHttpInfo
     *
     * Ermöglicht es, den korrigierten Praktikumsbericht für den angegebenen Teilnehmer zu melden
     *
     * @param  string $ausbildungszugabschnitt_id ID des Ausbildungszugabschnitts (required)
     * @param  string $teilnehmer_id ID des Teilnehmers (required)
     * @param  \Leifos\VedaConnector\GeneratedOpenApi\Model\PraktikumsberichtKorrigiertApiDto $praktikumsbericht_korrigiert_api_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['meldePraktikumsberichtKorrigiert'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function meldePraktikumsberichtKorrigiertAsyncWithHttpInfo($ausbildungszugabschnitt_id, $teilnehmer_id, $praktikumsbericht_korrigiert_api_dto, string $contentType = self::contentTypes['meldePraktikumsberichtKorrigiert'][0])
    {
        $returnType = '';
        $request = $this->meldePraktikumsberichtKorrigiertRequest($ausbildungszugabschnitt_id, $teilnehmer_id, $praktikumsbericht_korrigiert_api_dto, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'meldePraktikumsberichtKorrigiert'
     *
     * @param  string $ausbildungszugabschnitt_id ID des Ausbildungszugabschnitts (required)
     * @param  string $teilnehmer_id ID des Teilnehmers (required)
     * @param  \Leifos\VedaConnector\GeneratedOpenApi\Model\PraktikumsberichtKorrigiertApiDto $praktikumsbericht_korrigiert_api_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['meldePraktikumsberichtKorrigiert'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function meldePraktikumsberichtKorrigiertRequest($ausbildungszugabschnitt_id, $teilnehmer_id, $praktikumsbericht_korrigiert_api_dto, string $contentType = self::contentTypes['meldePraktikumsberichtKorrigiert'][0])
    {

        // verify the required parameter 'ausbildungszugabschnitt_id' is set
        if ($ausbildungszugabschnitt_id === null || (is_array($ausbildungszugabschnitt_id) && count($ausbildungszugabschnitt_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ausbildungszugabschnitt_id when calling meldePraktikumsberichtKorrigiert'
            );
        }

        // verify the required parameter 'teilnehmer_id' is set
        if ($teilnehmer_id === null || (is_array($teilnehmer_id) && count($teilnehmer_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $teilnehmer_id when calling meldePraktikumsberichtKorrigiert'
            );
        }

        // verify the required parameter 'praktikumsbericht_korrigiert_api_dto' is set
        if ($praktikumsbericht_korrigiert_api_dto === null || (is_array($praktikumsbericht_korrigiert_api_dto) && count($praktikumsbericht_korrigiert_api_dto) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $praktikumsbericht_korrigiert_api_dto when calling meldePraktikumsberichtKorrigiert'
            );
        }


        $resourcePath = '/v2/ausbildungszugabschnitte/{ausbildungszugabschnittId}/teilnehmer/{teilnehmerId}/meldepraktikumsberichtkorrigiert';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($ausbildungszugabschnitt_id !== null) {
            $resourcePath = str_replace(
                '{ausbildungszugabschnittId}',
                ObjectSerializer::toPathValue($ausbildungszugabschnitt_id),
                $resourcePath
            );
        }
        // path params
        if ($teilnehmer_id !== null) {
            $resourcePath = str_replace(
                '{teilnehmerId}',
                ObjectSerializer::toPathValue($teilnehmer_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($praktikumsbericht_korrigiert_api_dto)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($praktikumsbericht_korrigiert_api_dto));
            } else {
                $httpBody = $praktikumsbericht_korrigiert_api_dto;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-jwp-apiaccesstoken');
        if ($apiKey !== null) {
            $headers['x-jwp-apiaccesstoken'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
