<?php
/**
 * Elearningkurs
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Leifos\VedaConnector\GeneratedOpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * VEDA Bildungsmanager API
 *
 * Dokumentation der REST-Schnittstellen des VEDA Bildungsmanagers. Die Dokumentation zu speziellen Versionen sind unter den jeweiligen Pfaden abrufbar, z.B.: ./api/docs/v1 für Version 1, /api/docs/v2 für Version 2.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Leifos\VedaConnector\GeneratedOpenApi\Model;

use \ArrayAccess;
use \Leifos\VedaConnector\GeneratedOpenApi\ObjectSerializer;

/**
 * Elearningkurs Class Doc Comment
 *
 * @category Class
 * @description Beschreibt einen E-Learning-Kurs zur Verwendung auf einer externen E-Learning-Plattform
 * @package  Leifos\VedaConnector\GeneratedOpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Elearningkurs implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'Elearningkurs';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'oid' => 'string',
        'bezeichnung' => 'string',
        'beschreibung' => 'string',
        'masterkurs' => 'string',
        'beginn' => '\DateTime',
        'ende' => '\DateTime',
        'kapazitaet' => 'int',
        'offline_anlegen' => 'bool',
        'kursabschluss_als_erfolg_dokumentieren' => 'bool',
        'termine' => '\Leifos\VedaConnector\GeneratedOpenApi\Model\ElearningkursZugeordneterTerminReihe[]',
        'terminreihen' => '\Leifos\VedaConnector\GeneratedOpenApi\Model\ElearningkursZugeordneterTerminReihe[]',
        'links' => '\Leifos\VedaConnector\GeneratedOpenApi\Model\Link[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'oid' => 'uuid',
        'bezeichnung' => null,
        'beschreibung' => null,
        'masterkurs' => null,
        'beginn' => 'date',
        'ende' => 'date',
        'kapazitaet' => null,
        'offline_anlegen' => null,
        'kursabschluss_als_erfolg_dokumentieren' => null,
        'termine' => null,
        'terminreihen' => null,
        'links' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'oid' => false,
        'bezeichnung' => false,
        'beschreibung' => false,
        'masterkurs' => false,
        'beginn' => false,
        'ende' => false,
        'kapazitaet' => false,
        'offline_anlegen' => false,
        'kursabschluss_als_erfolg_dokumentieren' => false,
        'termine' => false,
        'terminreihen' => false,
        'links' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'oid' => 'oid',
        'bezeichnung' => 'bezeichnung',
        'beschreibung' => 'beschreibung',
        'masterkurs' => 'masterkurs',
        'beginn' => 'beginn',
        'ende' => 'ende',
        'kapazitaet' => 'kapazitaet',
        'offline_anlegen' => 'offlineAnlegen',
        'kursabschluss_als_erfolg_dokumentieren' => 'kursabschlussAlsErfolgDokumentieren',
        'termine' => 'termine',
        'terminreihen' => 'terminreihen',
        'links' => 'links'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'oid' => 'setOid',
        'bezeichnung' => 'setBezeichnung',
        'beschreibung' => 'setBeschreibung',
        'masterkurs' => 'setMasterkurs',
        'beginn' => 'setBeginn',
        'ende' => 'setEnde',
        'kapazitaet' => 'setKapazitaet',
        'offline_anlegen' => 'setOfflineAnlegen',
        'kursabschluss_als_erfolg_dokumentieren' => 'setKursabschlussAlsErfolgDokumentieren',
        'termine' => 'setTermine',
        'terminreihen' => 'setTerminreihen',
        'links' => 'setLinks'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'oid' => 'getOid',
        'bezeichnung' => 'getBezeichnung',
        'beschreibung' => 'getBeschreibung',
        'masterkurs' => 'getMasterkurs',
        'beginn' => 'getBeginn',
        'ende' => 'getEnde',
        'kapazitaet' => 'getKapazitaet',
        'offline_anlegen' => 'getOfflineAnlegen',
        'kursabschluss_als_erfolg_dokumentieren' => 'getKursabschlussAlsErfolgDokumentieren',
        'termine' => 'getTermine',
        'terminreihen' => 'getTerminreihen',
        'links' => 'getLinks'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('oid', $data ?? [], null);
        $this->setIfExists('bezeichnung', $data ?? [], null);
        $this->setIfExists('beschreibung', $data ?? [], null);
        $this->setIfExists('masterkurs', $data ?? [], null);
        $this->setIfExists('beginn', $data ?? [], null);
        $this->setIfExists('ende', $data ?? [], null);
        $this->setIfExists('kapazitaet', $data ?? [], null);
        $this->setIfExists('offline_anlegen', $data ?? [], null);
        $this->setIfExists('kursabschluss_als_erfolg_dokumentieren', $data ?? [], null);
        $this->setIfExists('termine', $data ?? [], null);
        $this->setIfExists('terminreihen', $data ?? [], null);
        $this->setIfExists('links', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['oid'] === null) {
            $invalidProperties[] = "'oid' can't be null";
        }
        if ($this->container['bezeichnung'] === null) {
            $invalidProperties[] = "'bezeichnung' can't be null";
        }
        if ($this->container['masterkurs'] === null) {
            $invalidProperties[] = "'masterkurs' can't be null";
        }
        if ($this->container['beginn'] === null) {
            $invalidProperties[] = "'beginn' can't be null";
        }
        if ($this->container['kursabschluss_als_erfolg_dokumentieren'] === null) {
            $invalidProperties[] = "'kursabschluss_als_erfolg_dokumentieren' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets oid
     *
     * @return string
     */
    public function getOid()
    {
        return $this->container['oid'];
    }

    /**
     * Sets oid
     *
     * @param string $oid UUID des Datensatzes
     *
     * @return self
     */
    public function setOid($oid)
    {
        if (is_null($oid)) {
            throw new \InvalidArgumentException('non-nullable oid cannot be null');
        }
        $this->container['oid'] = $oid;

        return $this;
    }

    /**
     * Gets bezeichnung
     *
     * @return string
     */
    public function getBezeichnung()
    {
        return $this->container['bezeichnung'];
    }

    /**
     * Sets bezeichnung
     *
     * @param string $bezeichnung Eindeutige Bezeichnung des E-Learning-Kurses. Hinweis: Das Format kann versionsabhängig variieren. Zur Ermittlung der einzelnen Werte (insb. Beginn Datum der Veranstaltung) bitte die entsprechend vorgesehenen Felder verwenden.
     *
     * @return self
     */
    public function setBezeichnung($bezeichnung)
    {
        if (is_null($bezeichnung)) {
            throw new \InvalidArgumentException('non-nullable bezeichnung cannot be null');
        }
        $this->container['bezeichnung'] = $bezeichnung;

        return $this;
    }

    /**
     * Gets beschreibung
     *
     * @return string|null
     */
    public function getBeschreibung()
    {
        return $this->container['beschreibung'];
    }

    /**
     * Sets beschreibung
     *
     * @param string|null $beschreibung Beschreibung des E-Learning-Kurses.
     *
     * @return self
     */
    public function setBeschreibung($beschreibung)
    {
        if (is_null($beschreibung)) {
            throw new \InvalidArgumentException('non-nullable beschreibung cannot be null');
        }
        $this->container['beschreibung'] = $beschreibung;

        return $this;
    }

    /**
     * Gets masterkurs
     *
     * @return string
     */
    public function getMasterkurs()
    {
        return $this->container['masterkurs'];
    }

    /**
     * Sets masterkurs
     *
     * @param string $masterkurs Die eindeutige ID des Masterkurses im externen System.
     *
     * @return self
     */
    public function setMasterkurs($masterkurs)
    {
        if (is_null($masterkurs)) {
            throw new \InvalidArgumentException('non-nullable masterkurs cannot be null');
        }
        $this->container['masterkurs'] = $masterkurs;

        return $this;
    }

    /**
     * Gets beginn
     *
     * @return \DateTime
     */
    public function getBeginn()
    {
        return $this->container['beginn'];
    }

    /**
     * Sets beginn
     *
     * @param \DateTime $beginn Das Tagesdatum, an dem der Kurs beginnt.
     *
     * @return self
     */
    public function setBeginn($beginn)
    {
        if (is_null($beginn)) {
            throw new \InvalidArgumentException('non-nullable beginn cannot be null');
        }
        $this->container['beginn'] = $beginn;

        return $this;
    }

    /**
     * Gets ende
     *
     * @return \DateTime|null
     */
    public function getEnde()
    {
        return $this->container['ende'];
    }

    /**
     * Sets ende
     *
     * @param \DateTime|null $ende Das Tagesdatum, an dem der Kurs endet.
     *
     * @return self
     */
    public function setEnde($ende)
    {
        if (is_null($ende)) {
            throw new \InvalidArgumentException('non-nullable ende cannot be null');
        }
        $this->container['ende'] = $ende;

        return $this;
    }

    /**
     * Gets kapazitaet
     *
     * @return int|null
     */
    public function getKapazitaet()
    {
        return $this->container['kapazitaet'];
    }

    /**
     * Sets kapazitaet
     *
     * @param int|null $kapazitaet Die maximale Anzahl an Teilnehmer, die der Kurs unterstützt.
     *
     * @return self
     */
    public function setKapazitaet($kapazitaet)
    {
        if (is_null($kapazitaet)) {
            throw new \InvalidArgumentException('non-nullable kapazitaet cannot be null');
        }
        $this->container['kapazitaet'] = $kapazitaet;

        return $this;
    }

    /**
     * Gets offline_anlegen
     *
     * @return bool|null
     */
    public function getOfflineAnlegen()
    {
        return $this->container['offline_anlegen'];
    }

    /**
     * Sets offline_anlegen
     *
     * @param bool|null $offline_anlegen Steuert, ob der Kurs im Status 'Online' oder 'Offline' angelegt werden soll.
     *
     * @return self
     */
    public function setOfflineAnlegen($offline_anlegen)
    {
        if (is_null($offline_anlegen)) {
            throw new \InvalidArgumentException('non-nullable offline_anlegen cannot be null');
        }
        $this->container['offline_anlegen'] = $offline_anlegen;

        return $this;
    }

    /**
     * Gets kursabschluss_als_erfolg_dokumentieren
     *
     * @return bool
     */
    public function getKursabschlussAlsErfolgDokumentieren()
    {
        return $this->container['kursabschluss_als_erfolg_dokumentieren'];
    }

    /**
     * Sets kursabschluss_als_erfolg_dokumentieren
     *
     * @param bool $kursabschluss_als_erfolg_dokumentieren Gibt an, ob die Meldung des Kursabschlusses als Lernerfolg dokumentiert wird.
     *
     * @return self
     */
    public function setKursabschlussAlsErfolgDokumentieren($kursabschluss_als_erfolg_dokumentieren)
    {
        if (is_null($kursabschluss_als_erfolg_dokumentieren)) {
            throw new \InvalidArgumentException('non-nullable kursabschluss_als_erfolg_dokumentieren cannot be null');
        }
        $this->container['kursabschluss_als_erfolg_dokumentieren'] = $kursabschluss_als_erfolg_dokumentieren;

        return $this;
    }

    /**
     * Gets termine
     *
     * @return \Leifos\VedaConnector\GeneratedOpenApi\Model\ElearningkursZugeordneterTerminReihe[]|null
     */
    public function getTermine()
    {
        return $this->container['termine'];
    }

    /**
     * Sets termine
     *
     * @param \Leifos\VedaConnector\GeneratedOpenApi\Model\ElearningkursZugeordneterTerminReihe[]|null $termine Gibt Informationen zu den zugeordneten Terminen an.
     *
     * @return self
     */
    public function setTermine($termine)
    {
        if (is_null($termine)) {
            throw new \InvalidArgumentException('non-nullable termine cannot be null');
        }
        $this->container['termine'] = $termine;

        return $this;
    }

    /**
     * Gets terminreihen
     *
     * @return \Leifos\VedaConnector\GeneratedOpenApi\Model\ElearningkursZugeordneterTerminReihe[]|null
     */
    public function getTerminreihen()
    {
        return $this->container['terminreihen'];
    }

    /**
     * Sets terminreihen
     *
     * @param \Leifos\VedaConnector\GeneratedOpenApi\Model\ElearningkursZugeordneterTerminReihe[]|null $terminreihen Gibt Informationen zu den zugeordneten Terminreihen an.
     *
     * @return self
     */
    public function setTerminreihen($terminreihen)
    {
        if (is_null($terminreihen)) {
            throw new \InvalidArgumentException('non-nullable terminreihen cannot be null');
        }
        $this->container['terminreihen'] = $terminreihen;

        return $this;
    }

    /**
     * Gets links
     *
     * @return \Leifos\VedaConnector\GeneratedOpenApi\Model\Link[]|null
     */
    public function getLinks()
    {
        return $this->container['links'];
    }

    /**
     * Sets links
     *
     * @param \Leifos\VedaConnector\GeneratedOpenApi\Model\Link[]|null $links links
     *
     * @return self
     */
    public function setLinks($links)
    {
        if (is_null($links)) {
            throw new \InvalidArgumentException('non-nullable links cannot be null');
        }
        $this->container['links'] = $links;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


