<?php
/**
 * LocalTime
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Leifos\VedaConnector\GeneratedOpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * VEDA Bildungsmanager API
 *
 * Dokumentation der REST-Schnittstellen des VEDA Bildungsmanagers. Die Dokumentation zu speziellen Versionen sind unter den jeweiligen Pfaden abrufbar, z.B.: ./api/docs/v1 für Version 1, /api/docs/v2 für Version 2.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Leifos\VedaConnector\GeneratedOpenApi\Model;

use \ArrayAccess;
use \Leifos\VedaConnector\GeneratedOpenApi\ObjectSerializer;

/**
 * LocalTime Class Doc Comment
 *
 * @category Class
 * @description Reguläres Ende des Veranstaltungstermins
 * @package  Leifos\VedaConnector\GeneratedOpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class LocalTime implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'LocalTime';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'chronology' => '\Leifos\VedaConnector\GeneratedOpenApi\Model\Chronology',
        'second_of_minute' => 'int',
        'hour_of_day' => 'int',
        'minute_of_hour' => 'int',
        'millis_of_day' => 'int',
        'millis_of_second' => 'int',
        'fields' => '\Leifos\VedaConnector\GeneratedOpenApi\Model\DateTimeField[]',
        'values' => 'int[]',
        'field_types' => '\Leifos\VedaConnector\GeneratedOpenApi\Model\DateTimeFieldType[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'chronology' => null,
        'second_of_minute' => 'int32',
        'hour_of_day' => 'int32',
        'minute_of_hour' => 'int32',
        'millis_of_day' => 'int32',
        'millis_of_second' => 'int32',
        'fields' => null,
        'values' => 'int32',
        'field_types' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'chronology' => false,
        'second_of_minute' => false,
        'hour_of_day' => false,
        'minute_of_hour' => false,
        'millis_of_day' => false,
        'millis_of_second' => false,
        'fields' => false,
        'values' => false,
        'field_types' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'chronology' => 'chronology',
        'second_of_minute' => 'secondOfMinute',
        'hour_of_day' => 'hourOfDay',
        'minute_of_hour' => 'minuteOfHour',
        'millis_of_day' => 'millisOfDay',
        'millis_of_second' => 'millisOfSecond',
        'fields' => 'fields',
        'values' => 'values',
        'field_types' => 'fieldTypes'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'chronology' => 'setChronology',
        'second_of_minute' => 'setSecondOfMinute',
        'hour_of_day' => 'setHourOfDay',
        'minute_of_hour' => 'setMinuteOfHour',
        'millis_of_day' => 'setMillisOfDay',
        'millis_of_second' => 'setMillisOfSecond',
        'fields' => 'setFields',
        'values' => 'setValues',
        'field_types' => 'setFieldTypes'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'chronology' => 'getChronology',
        'second_of_minute' => 'getSecondOfMinute',
        'hour_of_day' => 'getHourOfDay',
        'minute_of_hour' => 'getMinuteOfHour',
        'millis_of_day' => 'getMillisOfDay',
        'millis_of_second' => 'getMillisOfSecond',
        'fields' => 'getFields',
        'values' => 'getValues',
        'field_types' => 'getFieldTypes'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('chronology', $data ?? [], null);
        $this->setIfExists('second_of_minute', $data ?? [], null);
        $this->setIfExists('hour_of_day', $data ?? [], null);
        $this->setIfExists('minute_of_hour', $data ?? [], null);
        $this->setIfExists('millis_of_day', $data ?? [], null);
        $this->setIfExists('millis_of_second', $data ?? [], null);
        $this->setIfExists('fields', $data ?? [], null);
        $this->setIfExists('values', $data ?? [], null);
        $this->setIfExists('field_types', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets chronology
     *
     * @return \Leifos\VedaConnector\GeneratedOpenApi\Model\Chronology|null
     */
    public function getChronology()
    {
        return $this->container['chronology'];
    }

    /**
     * Sets chronology
     *
     * @param \Leifos\VedaConnector\GeneratedOpenApi\Model\Chronology|null $chronology chronology
     *
     * @return self
     */
    public function setChronology($chronology)
    {
        if (is_null($chronology)) {
            throw new \InvalidArgumentException('non-nullable chronology cannot be null');
        }
        $this->container['chronology'] = $chronology;

        return $this;
    }

    /**
     * Gets second_of_minute
     *
     * @return int|null
     */
    public function getSecondOfMinute()
    {
        return $this->container['second_of_minute'];
    }

    /**
     * Sets second_of_minute
     *
     * @param int|null $second_of_minute second_of_minute
     *
     * @return self
     */
    public function setSecondOfMinute($second_of_minute)
    {
        if (is_null($second_of_minute)) {
            throw new \InvalidArgumentException('non-nullable second_of_minute cannot be null');
        }
        $this->container['second_of_minute'] = $second_of_minute;

        return $this;
    }

    /**
     * Gets hour_of_day
     *
     * @return int|null
     */
    public function getHourOfDay()
    {
        return $this->container['hour_of_day'];
    }

    /**
     * Sets hour_of_day
     *
     * @param int|null $hour_of_day hour_of_day
     *
     * @return self
     */
    public function setHourOfDay($hour_of_day)
    {
        if (is_null($hour_of_day)) {
            throw new \InvalidArgumentException('non-nullable hour_of_day cannot be null');
        }
        $this->container['hour_of_day'] = $hour_of_day;

        return $this;
    }

    /**
     * Gets minute_of_hour
     *
     * @return int|null
     */
    public function getMinuteOfHour()
    {
        return $this->container['minute_of_hour'];
    }

    /**
     * Sets minute_of_hour
     *
     * @param int|null $minute_of_hour minute_of_hour
     *
     * @return self
     */
    public function setMinuteOfHour($minute_of_hour)
    {
        if (is_null($minute_of_hour)) {
            throw new \InvalidArgumentException('non-nullable minute_of_hour cannot be null');
        }
        $this->container['minute_of_hour'] = $minute_of_hour;

        return $this;
    }

    /**
     * Gets millis_of_day
     *
     * @return int|null
     */
    public function getMillisOfDay()
    {
        return $this->container['millis_of_day'];
    }

    /**
     * Sets millis_of_day
     *
     * @param int|null $millis_of_day millis_of_day
     *
     * @return self
     */
    public function setMillisOfDay($millis_of_day)
    {
        if (is_null($millis_of_day)) {
            throw new \InvalidArgumentException('non-nullable millis_of_day cannot be null');
        }
        $this->container['millis_of_day'] = $millis_of_day;

        return $this;
    }

    /**
     * Gets millis_of_second
     *
     * @return int|null
     */
    public function getMillisOfSecond()
    {
        return $this->container['millis_of_second'];
    }

    /**
     * Sets millis_of_second
     *
     * @param int|null $millis_of_second millis_of_second
     *
     * @return self
     */
    public function setMillisOfSecond($millis_of_second)
    {
        if (is_null($millis_of_second)) {
            throw new \InvalidArgumentException('non-nullable millis_of_second cannot be null');
        }
        $this->container['millis_of_second'] = $millis_of_second;

        return $this;
    }

    /**
     * Gets fields
     *
     * @return \Leifos\VedaConnector\GeneratedOpenApi\Model\DateTimeField[]|null
     */
    public function getFields()
    {
        return $this->container['fields'];
    }

    /**
     * Sets fields
     *
     * @param \Leifos\VedaConnector\GeneratedOpenApi\Model\DateTimeField[]|null $fields fields
     *
     * @return self
     */
    public function setFields($fields)
    {
        if (is_null($fields)) {
            throw new \InvalidArgumentException('non-nullable fields cannot be null');
        }
        $this->container['fields'] = $fields;

        return $this;
    }

    /**
     * Gets values
     *
     * @return int[]|null
     */
    public function getValues()
    {
        return $this->container['values'];
    }

    /**
     * Sets values
     *
     * @param int[]|null $values values
     *
     * @return self
     */
    public function setValues($values)
    {
        if (is_null($values)) {
            throw new \InvalidArgumentException('non-nullable values cannot be null');
        }
        $this->container['values'] = $values;

        return $this;
    }

    /**
     * Gets field_types
     *
     * @return \Leifos\VedaConnector\GeneratedOpenApi\Model\DateTimeFieldType[]|null
     */
    public function getFieldTypes()
    {
        return $this->container['field_types'];
    }

    /**
     * Sets field_types
     *
     * @param \Leifos\VedaConnector\GeneratedOpenApi\Model\DateTimeFieldType[]|null $field_types field_types
     *
     * @return self
     */
    public function setFieldTypes($field_types)
    {
        if (is_null($field_types)) {
            throw new \InvalidArgumentException('non-nullable field_types cannot be null');
        }
        $this->container['field_types'] = $field_types;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


