<?php
/**
 * PLZBereichVeranstaltungstyp
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Leifos\VedaConnector\GeneratedOpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * VEDA Bildungsmanager API
 *
 * Dokumentation der REST-Schnittstellen des VEDA Bildungsmanagers. Die Dokumentation zu speziellen Versionen sind unter den jeweiligen Pfaden abrufbar, z.B.: ./api/docs/v1 für Version 1, /api/docs/v2 für Version 2.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Leifos\VedaConnector\GeneratedOpenApi\Model;

use \ArrayAccess;
use \Leifos\VedaConnector\GeneratedOpenApi\ObjectSerializer;

/**
 * PLZBereichVeranstaltungstyp Class Doc Comment
 *
 * @category Class
 * @description Ein PLZ-Bereich, der dem Veranstaltungstyp zugeordnet ist.
 * @package  Leifos\VedaConnector\GeneratedOpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PLZBereichVeranstaltungstyp implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'PLZ-Bereich_Veranstaltungstyp';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'uuid_des_datensatzes' => 'string',
        'veranstaltungstyp_id' => 'string',
        'veranstaltungsort' => '\Leifos\VedaConnector\GeneratedOpenApi\Model\Veranstaltungsort',
        'plz_von' => 'string',
        'plz_bis' => 'string',
        'links' => '\Leifos\VedaConnector\GeneratedOpenApi\Model\Link[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'uuid_des_datensatzes' => 'uuid',
        'veranstaltungstyp_id' => 'uuid',
        'veranstaltungsort' => null,
        'plz_von' => null,
        'plz_bis' => null,
        'links' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'uuid_des_datensatzes' => false,
        'veranstaltungstyp_id' => false,
        'veranstaltungsort' => false,
        'plz_von' => false,
        'plz_bis' => false,
        'links' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'uuid_des_datensatzes' => 'UUID des Datensatzes',
        'veranstaltungstyp_id' => 'veranstaltungstypID',
        'veranstaltungsort' => 'veranstaltungsort',
        'plz_von' => 'plzVon',
        'plz_bis' => 'plzBis',
        'links' => 'links'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'uuid_des_datensatzes' => 'setUuidDesDatensatzes',
        'veranstaltungstyp_id' => 'setVeranstaltungstypId',
        'veranstaltungsort' => 'setVeranstaltungsort',
        'plz_von' => 'setPlzVon',
        'plz_bis' => 'setPlzBis',
        'links' => 'setLinks'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'uuid_des_datensatzes' => 'getUuidDesDatensatzes',
        'veranstaltungstyp_id' => 'getVeranstaltungstypId',
        'veranstaltungsort' => 'getVeranstaltungsort',
        'plz_von' => 'getPlzVon',
        'plz_bis' => 'getPlzBis',
        'links' => 'getLinks'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('uuid_des_datensatzes', $data ?? [], null);
        $this->setIfExists('veranstaltungstyp_id', $data ?? [], null);
        $this->setIfExists('veranstaltungsort', $data ?? [], null);
        $this->setIfExists('plz_von', $data ?? [], null);
        $this->setIfExists('plz_bis', $data ?? [], null);
        $this->setIfExists('links', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['uuid_des_datensatzes'] === null) {
            $invalidProperties[] = "'uuid_des_datensatzes' can't be null";
        }
        if ($this->container['veranstaltungstyp_id'] === null) {
            $invalidProperties[] = "'veranstaltungstyp_id' can't be null";
        }
        if ($this->container['plz_von'] === null) {
            $invalidProperties[] = "'plz_von' can't be null";
        }
        if ($this->container['plz_bis'] === null) {
            $invalidProperties[] = "'plz_bis' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets uuid_des_datensatzes
     *
     * @return string
     */
    public function getUuidDesDatensatzes()
    {
        return $this->container['uuid_des_datensatzes'];
    }

    /**
     * Sets uuid_des_datensatzes
     *
     * @param string $uuid_des_datensatzes uuid_des_datensatzes
     *
     * @return self
     */
    public function setUuidDesDatensatzes($uuid_des_datensatzes)
    {
        if (is_null($uuid_des_datensatzes)) {
            throw new \InvalidArgumentException('non-nullable uuid_des_datensatzes cannot be null');
        }
        $this->container['uuid_des_datensatzes'] = $uuid_des_datensatzes;

        return $this;
    }

    /**
     * Gets veranstaltungstyp_id
     *
     * @return string
     */
    public function getVeranstaltungstypId()
    {
        return $this->container['veranstaltungstyp_id'];
    }

    /**
     * Sets veranstaltungstyp_id
     *
     * @param string $veranstaltungstyp_id Die ID des Veranstaltungstyps des Postleitzahl-Bereichs.
     *
     * @return self
     */
    public function setVeranstaltungstypId($veranstaltungstyp_id)
    {
        if (is_null($veranstaltungstyp_id)) {
            throw new \InvalidArgumentException('non-nullable veranstaltungstyp_id cannot be null');
        }
        $this->container['veranstaltungstyp_id'] = $veranstaltungstyp_id;

        return $this;
    }

    /**
     * Gets veranstaltungsort
     *
     * @return \Leifos\VedaConnector\GeneratedOpenApi\Model\Veranstaltungsort|null
     */
    public function getVeranstaltungsort()
    {
        return $this->container['veranstaltungsort'];
    }

    /**
     * Sets veranstaltungsort
     *
     * @param \Leifos\VedaConnector\GeneratedOpenApi\Model\Veranstaltungsort|null $veranstaltungsort veranstaltungsort
     *
     * @return self
     */
    public function setVeranstaltungsort($veranstaltungsort)
    {
        if (is_null($veranstaltungsort)) {
            throw new \InvalidArgumentException('non-nullable veranstaltungsort cannot be null');
        }
        $this->container['veranstaltungsort'] = $veranstaltungsort;

        return $this;
    }

    /**
     * Gets plz_von
     *
     * @return string
     */
    public function getPlzVon()
    {
        return $this->container['plz_von'];
    }

    /**
     * Sets plz_von
     *
     * @param string $plz_von PLZ von
     *
     * @return self
     */
    public function setPlzVon($plz_von)
    {
        if (is_null($plz_von)) {
            throw new \InvalidArgumentException('non-nullable plz_von cannot be null');
        }
        $this->container['plz_von'] = $plz_von;

        return $this;
    }

    /**
     * Gets plz_bis
     *
     * @return string
     */
    public function getPlzBis()
    {
        return $this->container['plz_bis'];
    }

    /**
     * Sets plz_bis
     *
     * @param string $plz_bis PLZ bis
     *
     * @return self
     */
    public function setPlzBis($plz_bis)
    {
        if (is_null($plz_bis)) {
            throw new \InvalidArgumentException('non-nullable plz_bis cannot be null');
        }
        $this->container['plz_bis'] = $plz_bis;

        return $this;
    }

    /**
     * Gets links
     *
     * @return \Leifos\VedaConnector\GeneratedOpenApi\Model\Link[]|null
     */
    public function getLinks()
    {
        return $this->container['links'];
    }

    /**
     * Sets links
     *
     * @param \Leifos\VedaConnector\GeneratedOpenApi\Model\Link[]|null $links links
     *
     * @return self
     */
    public function setLinks($links)
    {
        if (is_null($links)) {
            throw new \InvalidArgumentException('non-nullable links cannot be null');
        }
        $this->container['links'] = $links;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


