<?php
/**
 * TeilnehmerELearningPlattform
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Leifos\VedaConnector\GeneratedOpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * VEDA Bildungsmanager API
 *
 * Dokumentation der REST-Schnittstellen des VEDA Bildungsmanagers. Die Dokumentation zu speziellen Versionen sind unter den jeweiligen Pfaden abrufbar, z.B.: ./api/docs/v1 für Version 1, /api/docs/v2 für Version 2.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Leifos\VedaConnector\GeneratedOpenApi\Model;

use \ArrayAccess;
use \Leifos\VedaConnector\GeneratedOpenApi\ObjectSerializer;

/**
 * TeilnehmerELearningPlattform Class Doc Comment
 *
 * @category Class
 * @description Teilnehmer einer E-Learning-Plattform mit relevanten Informationen.
 * @package  Leifos\VedaConnector\GeneratedOpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TeilnehmerELearningPlattform implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'TeilnehmerELearningPlattform';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'teilnehmer' => '\Leifos\VedaConnector\GeneratedOpenApi\Model\Teilnehmer',
        'benutzername' => 'string',
        'initiales_passwort' => 'string',
        'gueltig_ab' => '\DateTime',
        'gueltig_bis' => '\DateTime',
        'externe_referenz_nr' => 'string',
        'elearning_plattform_id' => 'string',
        'email' => 'string',
        'links' => '\Leifos\VedaConnector\GeneratedOpenApi\Model\Link[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'teilnehmer' => null,
        'benutzername' => null,
        'initiales_passwort' => null,
        'gueltig_ab' => 'date',
        'gueltig_bis' => 'date',
        'externe_referenz_nr' => null,
        'elearning_plattform_id' => null,
        'email' => null,
        'links' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'teilnehmer' => false,
        'benutzername' => false,
        'initiales_passwort' => false,
        'gueltig_ab' => false,
        'gueltig_bis' => false,
        'externe_referenz_nr' => false,
        'elearning_plattform_id' => false,
        'email' => false,
        'links' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'teilnehmer' => 'teilnehmer',
        'benutzername' => 'benutzername',
        'initiales_passwort' => 'initialesPasswort',
        'gueltig_ab' => 'gueltigAb',
        'gueltig_bis' => 'gueltigBis',
        'externe_referenz_nr' => 'externeReferenzNr',
        'elearning_plattform_id' => 'elearningPlattformId',
        'email' => 'email',
        'links' => 'links'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'teilnehmer' => 'setTeilnehmer',
        'benutzername' => 'setBenutzername',
        'initiales_passwort' => 'setInitialesPasswort',
        'gueltig_ab' => 'setGueltigAb',
        'gueltig_bis' => 'setGueltigBis',
        'externe_referenz_nr' => 'setExterneReferenzNr',
        'elearning_plattform_id' => 'setElearningPlattformId',
        'email' => 'setEmail',
        'links' => 'setLinks'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'teilnehmer' => 'getTeilnehmer',
        'benutzername' => 'getBenutzername',
        'initiales_passwort' => 'getInitialesPasswort',
        'gueltig_ab' => 'getGueltigAb',
        'gueltig_bis' => 'getGueltigBis',
        'externe_referenz_nr' => 'getExterneReferenzNr',
        'elearning_plattform_id' => 'getElearningPlattformId',
        'email' => 'getEmail',
        'links' => 'getLinks'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('teilnehmer', $data ?? [], null);
        $this->setIfExists('benutzername', $data ?? [], null);
        $this->setIfExists('initiales_passwort', $data ?? [], null);
        $this->setIfExists('gueltig_ab', $data ?? [], null);
        $this->setIfExists('gueltig_bis', $data ?? [], null);
        $this->setIfExists('externe_referenz_nr', $data ?? [], null);
        $this->setIfExists('elearning_plattform_id', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('links', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['teilnehmer'] === null) {
            $invalidProperties[] = "'teilnehmer' can't be null";
        }
        if ($this->container['gueltig_ab'] === null) {
            $invalidProperties[] = "'gueltig_ab' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets teilnehmer
     *
     * @return \Leifos\VedaConnector\GeneratedOpenApi\Model\Teilnehmer
     */
    public function getTeilnehmer()
    {
        return $this->container['teilnehmer'];
    }

    /**
     * Sets teilnehmer
     *
     * @param \Leifos\VedaConnector\GeneratedOpenApi\Model\Teilnehmer $teilnehmer teilnehmer
     *
     * @return self
     */
    public function setTeilnehmer($teilnehmer)
    {
        if (is_null($teilnehmer)) {
            throw new \InvalidArgumentException('non-nullable teilnehmer cannot be null');
        }
        $this->container['teilnehmer'] = $teilnehmer;

        return $this;
    }

    /**
     * Gets benutzername
     *
     * @return string|null
     */
    public function getBenutzername()
    {
        return $this->container['benutzername'];
    }

    /**
     * Sets benutzername
     *
     * @param string|null $benutzername Der Benutzername für die E-Learning-Plattform
     *
     * @return self
     */
    public function setBenutzername($benutzername)
    {
        if (is_null($benutzername)) {
            throw new \InvalidArgumentException('non-nullable benutzername cannot be null');
        }
        $this->container['benutzername'] = $benutzername;

        return $this;
    }

    /**
     * Gets initiales_passwort
     *
     * @return string|null
     */
    public function getInitialesPasswort()
    {
        return $this->container['initiales_passwort'];
    }

    /**
     * Sets initiales_passwort
     *
     * @param string|null $initiales_passwort Das initiale Passwort für die E-Learning-Plattform
     *
     * @return self
     */
    public function setInitialesPasswort($initiales_passwort)
    {
        if (is_null($initiales_passwort)) {
            throw new \InvalidArgumentException('non-nullable initiales_passwort cannot be null');
        }
        $this->container['initiales_passwort'] = $initiales_passwort;

        return $this;
    }

    /**
     * Gets gueltig_ab
     *
     * @return \DateTime
     */
    public function getGueltigAb()
    {
        return $this->container['gueltig_ab'];
    }

    /**
     * Sets gueltig_ab
     *
     * @param \DateTime $gueltig_ab Gültig ab des E-Learning-Benutzeraccounts
     *
     * @return self
     */
    public function setGueltigAb($gueltig_ab)
    {
        if (is_null($gueltig_ab)) {
            throw new \InvalidArgumentException('non-nullable gueltig_ab cannot be null');
        }
        $this->container['gueltig_ab'] = $gueltig_ab;

        return $this;
    }

    /**
     * Gets gueltig_bis
     *
     * @return \DateTime|null
     */
    public function getGueltigBis()
    {
        return $this->container['gueltig_bis'];
    }

    /**
     * Sets gueltig_bis
     *
     * @param \DateTime|null $gueltig_bis Gültig bis des E-Learning-Benutzeraccounts
     *
     * @return self
     */
    public function setGueltigBis($gueltig_bis)
    {
        if (is_null($gueltig_bis)) {
            throw new \InvalidArgumentException('non-nullable gueltig_bis cannot be null');
        }
        $this->container['gueltig_bis'] = $gueltig_bis;

        return $this;
    }

    /**
     * Gets externe_referenz_nr
     *
     * @return string|null
     */
    public function getExterneReferenzNr()
    {
        return $this->container['externe_referenz_nr'];
    }

    /**
     * Sets externe_referenz_nr
     *
     * @param string|null $externe_referenz_nr Die Nummer aus dem externen Partnersystem
     *
     * @return self
     */
    public function setExterneReferenzNr($externe_referenz_nr)
    {
        if (is_null($externe_referenz_nr)) {
            throw new \InvalidArgumentException('non-nullable externe_referenz_nr cannot be null');
        }
        $this->container['externe_referenz_nr'] = $externe_referenz_nr;

        return $this;
    }

    /**
     * Gets elearning_plattform_id
     *
     * @return string|null
     */
    public function getElearningPlattformId()
    {
        return $this->container['elearning_plattform_id'];
    }

    /**
     * Sets elearning_plattform_id
     *
     * @param string|null $elearning_plattform_id elearning_plattform_id
     *
     * @return self
     */
    public function setElearningPlattformId($elearning_plattform_id)
    {
        if (is_null($elearning_plattform_id)) {
            throw new \InvalidArgumentException('non-nullable elearning_plattform_id cannot be null');
        }
        $this->container['elearning_plattform_id'] = $elearning_plattform_id;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string|null $email email
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            throw new \InvalidArgumentException('non-nullable email cannot be null');
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets links
     *
     * @return \Leifos\VedaConnector\GeneratedOpenApi\Model\Link[]|null
     */
    public function getLinks()
    {
        return $this->container['links'];
    }

    /**
     * Sets links
     *
     * @param \Leifos\VedaConnector\GeneratedOpenApi\Model\Link[]|null $links links
     *
     * @return self
     */
    public function setLinks($links)
    {
        if (is_null($links)) {
            throw new \InvalidArgumentException('non-nullable links cannot be null');
        }
        $this->container['links'] = $links;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


