<?php
/**
 * TeilnehmerAktionStornierenApiDto
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Leifos\VedaConnector\GeneratedOpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * VEDA Bildungsmanager API
 *
 * Dokumentation der REST-Schnittstellen des VEDA Bildungsmanagers für die Version 2. Die Dokumentation zu speziellen Versionen kann über die Angabe des zusätzlichen Parameters \"group\" angezeigt werden. Beispiel: .../api/docs?group=v1 für die Dokumentation der Version 1, die aktuelle Version ist unter .../api/docs erreichbar.
 *
 * The version of the OpenAPI document: 2
 * Contact: info@veda.net
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Leifos\VedaConnector\GeneratedOpenApi\Model;

use \ArrayAccess;
use \Leifos\VedaConnector\GeneratedOpenApi\ObjectSerializer;

/**
 * TeilnehmerAktionStornierenApiDto Class Doc Comment
 *
 * @category Class
 * @package  Leifos\VedaConnector\GeneratedOpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TeilnehmerAktionStornierenApiDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TeilnehmerAktionStornierenApiDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'kuerzel_stornierungs_grund' => 'string',
        'links' => '\Leifos\VedaConnector\GeneratedOpenApi\Model\Link[]',
        'stornierungsdatum_fremdsystem' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'kuerzel_stornierungs_grund' => null,
        'links' => null,
        'stornierungsdatum_fremdsystem' => 'date'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'kuerzel_stornierungs_grund' => false,
		'links' => false,
		'stornierungsdatum_fremdsystem' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'kuerzel_stornierungs_grund' => 'kuerzelStornierungsGrund',
        'links' => 'links',
        'stornierungsdatum_fremdsystem' => 'stornierungsdatumFremdsystem'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'kuerzel_stornierungs_grund' => 'setKuerzelStornierungsGrund',
        'links' => 'setLinks',
        'stornierungsdatum_fremdsystem' => 'setStornierungsdatumFremdsystem'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'kuerzel_stornierungs_grund' => 'getKuerzelStornierungsGrund',
        'links' => 'getLinks',
        'stornierungsdatum_fremdsystem' => 'getStornierungsdatumFremdsystem'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('kuerzel_stornierungs_grund', $data ?? [], null);
        $this->setIfExists('links', $data ?? [], null);
        $this->setIfExists('stornierungsdatum_fremdsystem', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets kuerzel_stornierungs_grund
     *
     * @return string|null
     */
    public function getKuerzelStornierungsGrund()
    {
        return $this->container['kuerzel_stornierungs_grund'];
    }

    /**
     * Sets kuerzel_stornierungs_grund
     *
     * @param string|null $kuerzel_stornierungs_grund Ein Kürzel aus der Bildungsmanager-Tabelle Teilnehmerstornierungsgründe. Je nach Kürzel wird dann der dazu passende Teilnehmerstornierungsgrund gesetzt. Wird kein Teilnehmerstornierungsgrund gesetzt, so greift der in den Systemeinstellungen der REST-Schnittstelle hinterlegte Standardgrund. Ist hier nichts hinterlegt, kann nicht storniert werden.
     *
     * @return self
     */
    public function setKuerzelStornierungsGrund($kuerzel_stornierungs_grund)
    {
        if (is_null($kuerzel_stornierungs_grund)) {
            throw new \InvalidArgumentException('non-nullable kuerzel_stornierungs_grund cannot be null');
        }
        $this->container['kuerzel_stornierungs_grund'] = $kuerzel_stornierungs_grund;

        return $this;
    }

    /**
     * Gets links
     *
     * @return \Leifos\VedaConnector\GeneratedOpenApi\Model\Link[]|null
     */
    public function getLinks()
    {
        return $this->container['links'];
    }

    /**
     * Sets links
     *
     * @param \Leifos\VedaConnector\GeneratedOpenApi\Model\Link[]|null $links links
     *
     * @return self
     */
    public function setLinks($links)
    {
        if (is_null($links)) {
            throw new \InvalidArgumentException('non-nullable links cannot be null');
        }
        $this->container['links'] = $links;

        return $this;
    }

    /**
     * Gets stornierungsdatum_fremdsystem
     *
     * @return \DateTime|null
     */
    public function getStornierungsdatumFremdsystem()
    {
        return $this->container['stornierungsdatum_fremdsystem'];
    }

    /**
     * Sets stornierungsdatum_fremdsystem
     *
     * @param \DateTime|null $stornierungsdatum_fremdsystem Stornierungsdatum des aufrufenden Systems. Wird nichts gesetzt, wird mit dem aktuellen Tagesdatum des Bildungsmanager-Servers vorbelegt.
     *
     * @return self
     */
    public function setStornierungsdatumFremdsystem($stornierungsdatum_fremdsystem)
    {
        if (is_null($stornierungsdatum_fremdsystem)) {
            throw new \InvalidArgumentException('non-nullable stornierungsdatum_fremdsystem cannot be null');
        }
        $this->container['stornierungsdatum_fremdsystem'] = $stornierungsdatum_fremdsystem;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


