<?php
/**
 * VeranstaltungsterminreiheSIGUV
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Leifos\VedaConnector\GeneratedOpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * VEDA Bildungsmanager API
 *
 * Dokumentation der REST-Schnittstellen des VEDA Bildungsmanagers. Die Dokumentation zu speziellen Versionen sind unter den jeweiligen Pfaden abrufbar, z.B.: ./api/docs/v1 für Version 1, /api/docs/v2 für Version 2.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Leifos\VedaConnector\GeneratedOpenApi\Model;

use \ArrayAccess;
use \Leifos\VedaConnector\GeneratedOpenApi\ObjectSerializer;

/**
 * VeranstaltungsterminreiheSIGUV Class Doc Comment
 *
 * @category Class
 * @description Eine Veranstaltungsterminreihe mit ihren relevanten Daten
 * @package  Leifos\VedaConnector\GeneratedOpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class VeranstaltungsterminreiheSIGUV implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'Veranstaltungsterminreihe_SIGUV';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'uuid_des_datensatzes' => 'string',
        'veranstaltungsterminreihen_nr' => 'string',
        'veranstaltungstyp_id' => 'string',
        'veranstaltungs_nr' => 'string',
        'veranstaltungskategorie' => '\Leifos\VedaConnector\GeneratedOpenApi\Model\Veranstaltungskategorie',
        'veranstaltungsunterkategorie' => '\Leifos\VedaConnector\GeneratedOpenApi\Model\Veranstaltungsunterkategorie',
        'kategorien' => '\Leifos\VedaConnector\GeneratedOpenApi\Model\KategorieUndUnterkategorieApiDto[]',
        'thema' => 'string',
        'thema2' => 'string',
        'termin_von' => '\DateTime',
        'termin_bis' => '\DateTime',
        'teilnehmerminimum' => 'int',
        'teilnehmermaximum' => 'int',
        'wartelistenmaximum' => 'int',
        'anzahl_teilnehmerbuchungen' => 'int',
        'anzahl_wartelistenbuchungen' => 'int',
        'anzahl_freier_plaetze' => 'int',
        'anzahl_freier_wartelistenplaetze' => 'int',
        'auslastungsstatus' => 'string',
        'beschreibung' => 'string',
        'voraussetzung' => 'string',
        'ziel' => 'string',
        'inhalt' => 'string',
        'methodik' => 'string',
        'hinweise' => 'string',
        'sprache' => 'string',
        'beginn_des_anmeldezeitraums' => '\DateTime',
        'ende_des_anmeldezeitraums' => '\DateTime',
        'veranstaltungsanbieter' => '\Leifos\VedaConnector\GeneratedOpenApi\Model\Veranstaltungsanbieter',
        'veranstaltungsort' => '\Leifos\VedaConnector\GeneratedOpenApi\Model\Veranstaltungsort',
        'zielgruppen' => '\Leifos\VedaConnector\GeneratedOpenApi\Model\Zielgruppe[]',
        'schlagwoerter' => '\Leifos\VedaConnector\GeneratedOpenApi\Model\Schlagwort[]',
        'preis' => 'float',
        'preise_je_teilnehmergruppe' => '\Leifos\VedaConnector\GeneratedOpenApi\Model\TeilnehmergruppePreis[]',
        'sachbearbeiter' => '\Leifos\VedaConnector\GeneratedOpenApi\Model\Sachbearbeiter',
        'standardzahlungsbedingung' => '\Leifos\VedaConnector\GeneratedOpenApi\Model\Zahlungsbedingung',
        'termine' => '\Leifos\VedaConnector\GeneratedOpenApi\Model\VeranstaltungsterminDerReiheApiDto[]',
        'veranstaltungsform' => '\Leifos\VedaConnector\GeneratedOpenApi\Model\Veranstaltungsform',
        'geschlossen' => 'bool',
        'fachlicher_ansprechpartner' => '\Leifos\VedaConnector\GeneratedOpenApi\Model\Fachlicheransprechpartner',
        'veranstalter' => '\Leifos\VedaConnector\GeneratedOpenApi\Model\Veranstalter',
        'zusatzinformationen' => 'string',
        'mitzubringen_durch_teilnehmer' => 'string',
        'zielgruppen_details' => 'string',
        'sachbearbeiter_tn' => '\Leifos\VedaConnector\GeneratedOpenApi\Model\Sachbearbeiter',
        'links' => '\Leifos\VedaConnector\GeneratedOpenApi\Model\Link[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'uuid_des_datensatzes' => 'uuid',
        'veranstaltungsterminreihen_nr' => null,
        'veranstaltungstyp_id' => null,
        'veranstaltungs_nr' => null,
        'veranstaltungskategorie' => null,
        'veranstaltungsunterkategorie' => null,
        'kategorien' => null,
        'thema' => null,
        'thema2' => null,
        'termin_von' => 'date-time',
        'termin_bis' => 'date-time',
        'teilnehmerminimum' => null,
        'teilnehmermaximum' => null,
        'wartelistenmaximum' => null,
        'anzahl_teilnehmerbuchungen' => null,
        'anzahl_wartelistenbuchungen' => null,
        'anzahl_freier_plaetze' => null,
        'anzahl_freier_wartelistenplaetze' => null,
        'auslastungsstatus' => null,
        'beschreibung' => null,
        'voraussetzung' => null,
        'ziel' => null,
        'inhalt' => null,
        'methodik' => null,
        'hinweise' => null,
        'sprache' => null,
        'beginn_des_anmeldezeitraums' => 'date-time',
        'ende_des_anmeldezeitraums' => 'date-time',
        'veranstaltungsanbieter' => null,
        'veranstaltungsort' => null,
        'zielgruppen' => null,
        'schlagwoerter' => null,
        'preis' => null,
        'preise_je_teilnehmergruppe' => null,
        'sachbearbeiter' => null,
        'standardzahlungsbedingung' => null,
        'termine' => null,
        'veranstaltungsform' => null,
        'geschlossen' => null,
        'fachlicher_ansprechpartner' => null,
        'veranstalter' => null,
        'zusatzinformationen' => null,
        'mitzubringen_durch_teilnehmer' => null,
        'zielgruppen_details' => null,
        'sachbearbeiter_tn' => null,
        'links' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'uuid_des_datensatzes' => false,
        'veranstaltungsterminreihen_nr' => false,
        'veranstaltungstyp_id' => false,
        'veranstaltungs_nr' => false,
        'veranstaltungskategorie' => false,
        'veranstaltungsunterkategorie' => false,
        'kategorien' => false,
        'thema' => false,
        'thema2' => false,
        'termin_von' => false,
        'termin_bis' => false,
        'teilnehmerminimum' => false,
        'teilnehmermaximum' => false,
        'wartelistenmaximum' => false,
        'anzahl_teilnehmerbuchungen' => false,
        'anzahl_wartelistenbuchungen' => false,
        'anzahl_freier_plaetze' => false,
        'anzahl_freier_wartelistenplaetze' => false,
        'auslastungsstatus' => false,
        'beschreibung' => false,
        'voraussetzung' => false,
        'ziel' => false,
        'inhalt' => false,
        'methodik' => false,
        'hinweise' => false,
        'sprache' => false,
        'beginn_des_anmeldezeitraums' => false,
        'ende_des_anmeldezeitraums' => false,
        'veranstaltungsanbieter' => false,
        'veranstaltungsort' => false,
        'zielgruppen' => false,
        'schlagwoerter' => false,
        'preis' => false,
        'preise_je_teilnehmergruppe' => false,
        'sachbearbeiter' => false,
        'standardzahlungsbedingung' => false,
        'termine' => false,
        'veranstaltungsform' => false,
        'geschlossen' => false,
        'fachlicher_ansprechpartner' => false,
        'veranstalter' => false,
        'zusatzinformationen' => false,
        'mitzubringen_durch_teilnehmer' => false,
        'zielgruppen_details' => false,
        'sachbearbeiter_tn' => false,
        'links' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'uuid_des_datensatzes' => 'UUID des Datensatzes',
        'veranstaltungsterminreihen_nr' => 'veranstaltungsterminreihenNr',
        'veranstaltungstyp_id' => 'veranstaltungstypID',
        'veranstaltungs_nr' => 'veranstaltungsNr',
        'veranstaltungskategorie' => 'veranstaltungskategorie',
        'veranstaltungsunterkategorie' => 'veranstaltungsunterkategorie',
        'kategorien' => 'kategorien',
        'thema' => 'thema',
        'thema2' => 'thema2',
        'termin_von' => 'terminVon',
        'termin_bis' => 'terminBis',
        'teilnehmerminimum' => 'teilnehmerminimum',
        'teilnehmermaximum' => 'teilnehmermaximum',
        'wartelistenmaximum' => 'wartelistenmaximum',
        'anzahl_teilnehmerbuchungen' => 'anzahlTeilnehmerbuchungen',
        'anzahl_wartelistenbuchungen' => 'anzahlWartelistenbuchungen',
        'anzahl_freier_plaetze' => 'anzahlFreierPlaetze',
        'anzahl_freier_wartelistenplaetze' => 'anzahlFreierWartelistenplaetze',
        'auslastungsstatus' => 'auslastungsstatus',
        'beschreibung' => 'beschreibung',
        'voraussetzung' => 'voraussetzung',
        'ziel' => 'ziel',
        'inhalt' => 'inhalt',
        'methodik' => 'methodik',
        'hinweise' => 'hinweise',
        'sprache' => 'sprache',
        'beginn_des_anmeldezeitraums' => 'beginnDesAnmeldezeitraums',
        'ende_des_anmeldezeitraums' => 'endeDesAnmeldezeitraums',
        'veranstaltungsanbieter' => 'veranstaltungsanbieter',
        'veranstaltungsort' => 'veranstaltungsort',
        'zielgruppen' => 'zielgruppen',
        'schlagwoerter' => 'schlagwoerter',
        'preis' => 'preis',
        'preise_je_teilnehmergruppe' => 'preiseJeTeilnehmergruppe',
        'sachbearbeiter' => 'sachbearbeiter',
        'standardzahlungsbedingung' => 'standardzahlungsbedingung',
        'termine' => 'termine',
        'veranstaltungsform' => 'veranstaltungsform',
        'geschlossen' => 'geschlossen',
        'fachlicher_ansprechpartner' => 'fachlicherAnsprechpartner',
        'veranstalter' => 'veranstalter',
        'zusatzinformationen' => 'zusatzinformationen',
        'mitzubringen_durch_teilnehmer' => 'mitzubringenDurchTeilnehmer',
        'zielgruppen_details' => 'zielgruppenDetails',
        'sachbearbeiter_tn' => 'sachbearbeiterTn',
        'links' => 'links'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'uuid_des_datensatzes' => 'setUuidDesDatensatzes',
        'veranstaltungsterminreihen_nr' => 'setVeranstaltungsterminreihenNr',
        'veranstaltungstyp_id' => 'setVeranstaltungstypId',
        'veranstaltungs_nr' => 'setVeranstaltungsNr',
        'veranstaltungskategorie' => 'setVeranstaltungskategorie',
        'veranstaltungsunterkategorie' => 'setVeranstaltungsunterkategorie',
        'kategorien' => 'setKategorien',
        'thema' => 'setThema',
        'thema2' => 'setThema2',
        'termin_von' => 'setTerminVon',
        'termin_bis' => 'setTerminBis',
        'teilnehmerminimum' => 'setTeilnehmerminimum',
        'teilnehmermaximum' => 'setTeilnehmermaximum',
        'wartelistenmaximum' => 'setWartelistenmaximum',
        'anzahl_teilnehmerbuchungen' => 'setAnzahlTeilnehmerbuchungen',
        'anzahl_wartelistenbuchungen' => 'setAnzahlWartelistenbuchungen',
        'anzahl_freier_plaetze' => 'setAnzahlFreierPlaetze',
        'anzahl_freier_wartelistenplaetze' => 'setAnzahlFreierWartelistenplaetze',
        'auslastungsstatus' => 'setAuslastungsstatus',
        'beschreibung' => 'setBeschreibung',
        'voraussetzung' => 'setVoraussetzung',
        'ziel' => 'setZiel',
        'inhalt' => 'setInhalt',
        'methodik' => 'setMethodik',
        'hinweise' => 'setHinweise',
        'sprache' => 'setSprache',
        'beginn_des_anmeldezeitraums' => 'setBeginnDesAnmeldezeitraums',
        'ende_des_anmeldezeitraums' => 'setEndeDesAnmeldezeitraums',
        'veranstaltungsanbieter' => 'setVeranstaltungsanbieter',
        'veranstaltungsort' => 'setVeranstaltungsort',
        'zielgruppen' => 'setZielgruppen',
        'schlagwoerter' => 'setSchlagwoerter',
        'preis' => 'setPreis',
        'preise_je_teilnehmergruppe' => 'setPreiseJeTeilnehmergruppe',
        'sachbearbeiter' => 'setSachbearbeiter',
        'standardzahlungsbedingung' => 'setStandardzahlungsbedingung',
        'termine' => 'setTermine',
        'veranstaltungsform' => 'setVeranstaltungsform',
        'geschlossen' => 'setGeschlossen',
        'fachlicher_ansprechpartner' => 'setFachlicherAnsprechpartner',
        'veranstalter' => 'setVeranstalter',
        'zusatzinformationen' => 'setZusatzinformationen',
        'mitzubringen_durch_teilnehmer' => 'setMitzubringenDurchTeilnehmer',
        'zielgruppen_details' => 'setZielgruppenDetails',
        'sachbearbeiter_tn' => 'setSachbearbeiterTn',
        'links' => 'setLinks'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'uuid_des_datensatzes' => 'getUuidDesDatensatzes',
        'veranstaltungsterminreihen_nr' => 'getVeranstaltungsterminreihenNr',
        'veranstaltungstyp_id' => 'getVeranstaltungstypId',
        'veranstaltungs_nr' => 'getVeranstaltungsNr',
        'veranstaltungskategorie' => 'getVeranstaltungskategorie',
        'veranstaltungsunterkategorie' => 'getVeranstaltungsunterkategorie',
        'kategorien' => 'getKategorien',
        'thema' => 'getThema',
        'thema2' => 'getThema2',
        'termin_von' => 'getTerminVon',
        'termin_bis' => 'getTerminBis',
        'teilnehmerminimum' => 'getTeilnehmerminimum',
        'teilnehmermaximum' => 'getTeilnehmermaximum',
        'wartelistenmaximum' => 'getWartelistenmaximum',
        'anzahl_teilnehmerbuchungen' => 'getAnzahlTeilnehmerbuchungen',
        'anzahl_wartelistenbuchungen' => 'getAnzahlWartelistenbuchungen',
        'anzahl_freier_plaetze' => 'getAnzahlFreierPlaetze',
        'anzahl_freier_wartelistenplaetze' => 'getAnzahlFreierWartelistenplaetze',
        'auslastungsstatus' => 'getAuslastungsstatus',
        'beschreibung' => 'getBeschreibung',
        'voraussetzung' => 'getVoraussetzung',
        'ziel' => 'getZiel',
        'inhalt' => 'getInhalt',
        'methodik' => 'getMethodik',
        'hinweise' => 'getHinweise',
        'sprache' => 'getSprache',
        'beginn_des_anmeldezeitraums' => 'getBeginnDesAnmeldezeitraums',
        'ende_des_anmeldezeitraums' => 'getEndeDesAnmeldezeitraums',
        'veranstaltungsanbieter' => 'getVeranstaltungsanbieter',
        'veranstaltungsort' => 'getVeranstaltungsort',
        'zielgruppen' => 'getZielgruppen',
        'schlagwoerter' => 'getSchlagwoerter',
        'preis' => 'getPreis',
        'preise_je_teilnehmergruppe' => 'getPreiseJeTeilnehmergruppe',
        'sachbearbeiter' => 'getSachbearbeiter',
        'standardzahlungsbedingung' => 'getStandardzahlungsbedingung',
        'termine' => 'getTermine',
        'veranstaltungsform' => 'getVeranstaltungsform',
        'geschlossen' => 'getGeschlossen',
        'fachlicher_ansprechpartner' => 'getFachlicherAnsprechpartner',
        'veranstalter' => 'getVeranstalter',
        'zusatzinformationen' => 'getZusatzinformationen',
        'mitzubringen_durch_teilnehmer' => 'getMitzubringenDurchTeilnehmer',
        'zielgruppen_details' => 'getZielgruppenDetails',
        'sachbearbeiter_tn' => 'getSachbearbeiterTn',
        'links' => 'getLinks'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('uuid_des_datensatzes', $data ?? [], null);
        $this->setIfExists('veranstaltungsterminreihen_nr', $data ?? [], null);
        $this->setIfExists('veranstaltungstyp_id', $data ?? [], null);
        $this->setIfExists('veranstaltungs_nr', $data ?? [], null);
        $this->setIfExists('veranstaltungskategorie', $data ?? [], null);
        $this->setIfExists('veranstaltungsunterkategorie', $data ?? [], null);
        $this->setIfExists('kategorien', $data ?? [], null);
        $this->setIfExists('thema', $data ?? [], null);
        $this->setIfExists('thema2', $data ?? [], null);
        $this->setIfExists('termin_von', $data ?? [], null);
        $this->setIfExists('termin_bis', $data ?? [], null);
        $this->setIfExists('teilnehmerminimum', $data ?? [], null);
        $this->setIfExists('teilnehmermaximum', $data ?? [], null);
        $this->setIfExists('wartelistenmaximum', $data ?? [], null);
        $this->setIfExists('anzahl_teilnehmerbuchungen', $data ?? [], null);
        $this->setIfExists('anzahl_wartelistenbuchungen', $data ?? [], null);
        $this->setIfExists('anzahl_freier_plaetze', $data ?? [], null);
        $this->setIfExists('anzahl_freier_wartelistenplaetze', $data ?? [], null);
        $this->setIfExists('auslastungsstatus', $data ?? [], null);
        $this->setIfExists('beschreibung', $data ?? [], null);
        $this->setIfExists('voraussetzung', $data ?? [], null);
        $this->setIfExists('ziel', $data ?? [], null);
        $this->setIfExists('inhalt', $data ?? [], null);
        $this->setIfExists('methodik', $data ?? [], null);
        $this->setIfExists('hinweise', $data ?? [], null);
        $this->setIfExists('sprache', $data ?? [], null);
        $this->setIfExists('beginn_des_anmeldezeitraums', $data ?? [], null);
        $this->setIfExists('ende_des_anmeldezeitraums', $data ?? [], null);
        $this->setIfExists('veranstaltungsanbieter', $data ?? [], null);
        $this->setIfExists('veranstaltungsort', $data ?? [], null);
        $this->setIfExists('zielgruppen', $data ?? [], null);
        $this->setIfExists('schlagwoerter', $data ?? [], null);
        $this->setIfExists('preis', $data ?? [], null);
        $this->setIfExists('preise_je_teilnehmergruppe', $data ?? [], null);
        $this->setIfExists('sachbearbeiter', $data ?? [], null);
        $this->setIfExists('standardzahlungsbedingung', $data ?? [], null);
        $this->setIfExists('termine', $data ?? [], null);
        $this->setIfExists('veranstaltungsform', $data ?? [], null);
        $this->setIfExists('geschlossen', $data ?? [], null);
        $this->setIfExists('fachlicher_ansprechpartner', $data ?? [], null);
        $this->setIfExists('veranstalter', $data ?? [], null);
        $this->setIfExists('zusatzinformationen', $data ?? [], null);
        $this->setIfExists('mitzubringen_durch_teilnehmer', $data ?? [], null);
        $this->setIfExists('zielgruppen_details', $data ?? [], null);
        $this->setIfExists('sachbearbeiter_tn', $data ?? [], null);
        $this->setIfExists('links', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['uuid_des_datensatzes'] === null) {
            $invalidProperties[] = "'uuid_des_datensatzes' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets uuid_des_datensatzes
     *
     * @return string
     */
    public function getUuidDesDatensatzes()
    {
        return $this->container['uuid_des_datensatzes'];
    }

    /**
     * Sets uuid_des_datensatzes
     *
     * @param string $uuid_des_datensatzes uuid_des_datensatzes
     *
     * @return self
     */
    public function setUuidDesDatensatzes($uuid_des_datensatzes)
    {
        if (is_null($uuid_des_datensatzes)) {
            throw new \InvalidArgumentException('non-nullable uuid_des_datensatzes cannot be null');
        }
        $this->container['uuid_des_datensatzes'] = $uuid_des_datensatzes;

        return $this;
    }

    /**
     * Gets veranstaltungsterminreihen_nr
     *
     * @return string|null
     */
    public function getVeranstaltungsterminreihenNr()
    {
        return $this->container['veranstaltungsterminreihen_nr'];
    }

    /**
     * Sets veranstaltungsterminreihen_nr
     *
     * @param string|null $veranstaltungsterminreihen_nr veranstaltungsterminreihen_nr
     *
     * @return self
     */
    public function setVeranstaltungsterminreihenNr($veranstaltungsterminreihen_nr)
    {
        if (is_null($veranstaltungsterminreihen_nr)) {
            throw new \InvalidArgumentException('non-nullable veranstaltungsterminreihen_nr cannot be null');
        }
        $this->container['veranstaltungsterminreihen_nr'] = $veranstaltungsterminreihen_nr;

        return $this;
    }

    /**
     * Gets veranstaltungstyp_id
     *
     * @return string|null
     */
    public function getVeranstaltungstypId()
    {
        return $this->container['veranstaltungstyp_id'];
    }

    /**
     * Sets veranstaltungstyp_id
     *
     * @param string|null $veranstaltungstyp_id veranstaltungstyp_id
     *
     * @return self
     */
    public function setVeranstaltungstypId($veranstaltungstyp_id)
    {
        if (is_null($veranstaltungstyp_id)) {
            throw new \InvalidArgumentException('non-nullable veranstaltungstyp_id cannot be null');
        }
        $this->container['veranstaltungstyp_id'] = $veranstaltungstyp_id;

        return $this;
    }

    /**
     * Gets veranstaltungs_nr
     *
     * @return string|null
     */
    public function getVeranstaltungsNr()
    {
        return $this->container['veranstaltungs_nr'];
    }

    /**
     * Sets veranstaltungs_nr
     *
     * @param string|null $veranstaltungs_nr Die Veranstaltungs-Nr aus dem Veranstaltungstypen.
     *
     * @return self
     */
    public function setVeranstaltungsNr($veranstaltungs_nr)
    {
        if (is_null($veranstaltungs_nr)) {
            throw new \InvalidArgumentException('non-nullable veranstaltungs_nr cannot be null');
        }
        $this->container['veranstaltungs_nr'] = $veranstaltungs_nr;

        return $this;
    }

    /**
     * Gets veranstaltungskategorie
     *
     * @return \Leifos\VedaConnector\GeneratedOpenApi\Model\Veranstaltungskategorie|null
     */
    public function getVeranstaltungskategorie()
    {
        return $this->container['veranstaltungskategorie'];
    }

    /**
     * Sets veranstaltungskategorie
     *
     * @param \Leifos\VedaConnector\GeneratedOpenApi\Model\Veranstaltungskategorie|null $veranstaltungskategorie veranstaltungskategorie
     *
     * @return self
     */
    public function setVeranstaltungskategorie($veranstaltungskategorie)
    {
        if (is_null($veranstaltungskategorie)) {
            throw new \InvalidArgumentException('non-nullable veranstaltungskategorie cannot be null');
        }
        $this->container['veranstaltungskategorie'] = $veranstaltungskategorie;

        return $this;
    }

    /**
     * Gets veranstaltungsunterkategorie
     *
     * @return \Leifos\VedaConnector\GeneratedOpenApi\Model\Veranstaltungsunterkategorie|null
     */
    public function getVeranstaltungsunterkategorie()
    {
        return $this->container['veranstaltungsunterkategorie'];
    }

    /**
     * Sets veranstaltungsunterkategorie
     *
     * @param \Leifos\VedaConnector\GeneratedOpenApi\Model\Veranstaltungsunterkategorie|null $veranstaltungsunterkategorie veranstaltungsunterkategorie
     *
     * @return self
     */
    public function setVeranstaltungsunterkategorie($veranstaltungsunterkategorie)
    {
        if (is_null($veranstaltungsunterkategorie)) {
            throw new \InvalidArgumentException('non-nullable veranstaltungsunterkategorie cannot be null');
        }
        $this->container['veranstaltungsunterkategorie'] = $veranstaltungsunterkategorie;

        return $this;
    }

    /**
     * Gets kategorien
     *
     * @return \Leifos\VedaConnector\GeneratedOpenApi\Model\KategorieUndUnterkategorieApiDto[]|null
     */
    public function getKategorien()
    {
        return $this->container['kategorien'];
    }

    /**
     * Sets kategorien
     *
     * @param \Leifos\VedaConnector\GeneratedOpenApi\Model\KategorieUndUnterkategorieApiDto[]|null $kategorien Die Liste der Kategorien, die der Veranstaltungsterminreihe zugeordnet sind.
     *
     * @return self
     */
    public function setKategorien($kategorien)
    {
        if (is_null($kategorien)) {
            throw new \InvalidArgumentException('non-nullable kategorien cannot be null');
        }
        $this->container['kategorien'] = $kategorien;

        return $this;
    }

    /**
     * Gets thema
     *
     * @return string|null
     */
    public function getThema()
    {
        return $this->container['thema'];
    }

    /**
     * Sets thema
     *
     * @param string|null $thema thema
     *
     * @return self
     */
    public function setThema($thema)
    {
        if (is_null($thema)) {
            throw new \InvalidArgumentException('non-nullable thema cannot be null');
        }
        $this->container['thema'] = $thema;

        return $this;
    }

    /**
     * Gets thema2
     *
     * @return string|null
     */
    public function getThema2()
    {
        return $this->container['thema2'];
    }

    /**
     * Sets thema2
     *
     * @param string|null $thema2 thema2
     *
     * @return self
     */
    public function setThema2($thema2)
    {
        if (is_null($thema2)) {
            throw new \InvalidArgumentException('non-nullable thema2 cannot be null');
        }
        $this->container['thema2'] = $thema2;

        return $this;
    }

    /**
     * Gets termin_von
     *
     * @return \DateTime|null
     */
    public function getTerminVon()
    {
        return $this->container['termin_von'];
    }

    /**
     * Sets termin_von
     *
     * @param \DateTime|null $termin_von termin_von
     *
     * @return self
     */
    public function setTerminVon($termin_von)
    {
        if (is_null($termin_von)) {
            throw new \InvalidArgumentException('non-nullable termin_von cannot be null');
        }
        $this->container['termin_von'] = $termin_von;

        return $this;
    }

    /**
     * Gets termin_bis
     *
     * @return \DateTime|null
     */
    public function getTerminBis()
    {
        return $this->container['termin_bis'];
    }

    /**
     * Sets termin_bis
     *
     * @param \DateTime|null $termin_bis termin_bis
     *
     * @return self
     */
    public function setTerminBis($termin_bis)
    {
        if (is_null($termin_bis)) {
            throw new \InvalidArgumentException('non-nullable termin_bis cannot be null');
        }
        $this->container['termin_bis'] = $termin_bis;

        return $this;
    }

    /**
     * Gets teilnehmerminimum
     *
     * @return int|null
     */
    public function getTeilnehmerminimum()
    {
        return $this->container['teilnehmerminimum'];
    }

    /**
     * Sets teilnehmerminimum
     *
     * @param int|null $teilnehmerminimum teilnehmerminimum
     *
     * @return self
     */
    public function setTeilnehmerminimum($teilnehmerminimum)
    {
        if (is_null($teilnehmerminimum)) {
            throw new \InvalidArgumentException('non-nullable teilnehmerminimum cannot be null');
        }
        $this->container['teilnehmerminimum'] = $teilnehmerminimum;

        return $this;
    }

    /**
     * Gets teilnehmermaximum
     *
     * @return int|null
     */
    public function getTeilnehmermaximum()
    {
        return $this->container['teilnehmermaximum'];
    }

    /**
     * Sets teilnehmermaximum
     *
     * @param int|null $teilnehmermaximum teilnehmermaximum
     *
     * @return self
     */
    public function setTeilnehmermaximum($teilnehmermaximum)
    {
        if (is_null($teilnehmermaximum)) {
            throw new \InvalidArgumentException('non-nullable teilnehmermaximum cannot be null');
        }
        $this->container['teilnehmermaximum'] = $teilnehmermaximum;

        return $this;
    }

    /**
     * Gets wartelistenmaximum
     *
     * @return int|null
     */
    public function getWartelistenmaximum()
    {
        return $this->container['wartelistenmaximum'];
    }

    /**
     * Sets wartelistenmaximum
     *
     * @param int|null $wartelistenmaximum wartelistenmaximum
     *
     * @return self
     */
    public function setWartelistenmaximum($wartelistenmaximum)
    {
        if (is_null($wartelistenmaximum)) {
            throw new \InvalidArgumentException('non-nullable wartelistenmaximum cannot be null');
        }
        $this->container['wartelistenmaximum'] = $wartelistenmaximum;

        return $this;
    }

    /**
     * Gets anzahl_teilnehmerbuchungen
     *
     * @return int|null
     */
    public function getAnzahlTeilnehmerbuchungen()
    {
        return $this->container['anzahl_teilnehmerbuchungen'];
    }

    /**
     * Sets anzahl_teilnehmerbuchungen
     *
     * @param int|null $anzahl_teilnehmerbuchungen anzahl_teilnehmerbuchungen
     *
     * @return self
     */
    public function setAnzahlTeilnehmerbuchungen($anzahl_teilnehmerbuchungen)
    {
        if (is_null($anzahl_teilnehmerbuchungen)) {
            throw new \InvalidArgumentException('non-nullable anzahl_teilnehmerbuchungen cannot be null');
        }
        $this->container['anzahl_teilnehmerbuchungen'] = $anzahl_teilnehmerbuchungen;

        return $this;
    }

    /**
     * Gets anzahl_wartelistenbuchungen
     *
     * @return int|null
     */
    public function getAnzahlWartelistenbuchungen()
    {
        return $this->container['anzahl_wartelistenbuchungen'];
    }

    /**
     * Sets anzahl_wartelistenbuchungen
     *
     * @param int|null $anzahl_wartelistenbuchungen anzahl_wartelistenbuchungen
     *
     * @return self
     */
    public function setAnzahlWartelistenbuchungen($anzahl_wartelistenbuchungen)
    {
        if (is_null($anzahl_wartelistenbuchungen)) {
            throw new \InvalidArgumentException('non-nullable anzahl_wartelistenbuchungen cannot be null');
        }
        $this->container['anzahl_wartelistenbuchungen'] = $anzahl_wartelistenbuchungen;

        return $this;
    }

    /**
     * Gets anzahl_freier_plaetze
     *
     * @return int|null
     */
    public function getAnzahlFreierPlaetze()
    {
        return $this->container['anzahl_freier_plaetze'];
    }

    /**
     * Sets anzahl_freier_plaetze
     *
     * @param int|null $anzahl_freier_plaetze anzahl_freier_plaetze
     *
     * @return self
     */
    public function setAnzahlFreierPlaetze($anzahl_freier_plaetze)
    {
        if (is_null($anzahl_freier_plaetze)) {
            throw new \InvalidArgumentException('non-nullable anzahl_freier_plaetze cannot be null');
        }
        $this->container['anzahl_freier_plaetze'] = $anzahl_freier_plaetze;

        return $this;
    }

    /**
     * Gets anzahl_freier_wartelistenplaetze
     *
     * @return int|null
     */
    public function getAnzahlFreierWartelistenplaetze()
    {
        return $this->container['anzahl_freier_wartelistenplaetze'];
    }

    /**
     * Sets anzahl_freier_wartelistenplaetze
     *
     * @param int|null $anzahl_freier_wartelistenplaetze anzahl_freier_wartelistenplaetze
     *
     * @return self
     */
    public function setAnzahlFreierWartelistenplaetze($anzahl_freier_wartelistenplaetze)
    {
        if (is_null($anzahl_freier_wartelistenplaetze)) {
            throw new \InvalidArgumentException('non-nullable anzahl_freier_wartelistenplaetze cannot be null');
        }
        $this->container['anzahl_freier_wartelistenplaetze'] = $anzahl_freier_wartelistenplaetze;

        return $this;
    }

    /**
     * Gets auslastungsstatus
     *
     * @return string|null
     */
    public function getAuslastungsstatus()
    {
        return $this->container['auslastungsstatus'];
    }

    /**
     * Sets auslastungsstatus
     *
     * @param string|null $auslastungsstatus auslastungsstatus
     *
     * @return self
     */
    public function setAuslastungsstatus($auslastungsstatus)
    {
        if (is_null($auslastungsstatus)) {
            throw new \InvalidArgumentException('non-nullable auslastungsstatus cannot be null');
        }
        $this->container['auslastungsstatus'] = $auslastungsstatus;

        return $this;
    }

    /**
     * Gets beschreibung
     *
     * @return string|null
     */
    public function getBeschreibung()
    {
        return $this->container['beschreibung'];
    }

    /**
     * Sets beschreibung
     *
     * @param string|null $beschreibung beschreibung
     *
     * @return self
     */
    public function setBeschreibung($beschreibung)
    {
        if (is_null($beschreibung)) {
            throw new \InvalidArgumentException('non-nullable beschreibung cannot be null');
        }
        $this->container['beschreibung'] = $beschreibung;

        return $this;
    }

    /**
     * Gets voraussetzung
     *
     * @return string|null
     */
    public function getVoraussetzung()
    {
        return $this->container['voraussetzung'];
    }

    /**
     * Sets voraussetzung
     *
     * @param string|null $voraussetzung voraussetzung
     *
     * @return self
     */
    public function setVoraussetzung($voraussetzung)
    {
        if (is_null($voraussetzung)) {
            throw new \InvalidArgumentException('non-nullable voraussetzung cannot be null');
        }
        $this->container['voraussetzung'] = $voraussetzung;

        return $this;
    }

    /**
     * Gets ziel
     *
     * @return string|null
     */
    public function getZiel()
    {
        return $this->container['ziel'];
    }

    /**
     * Sets ziel
     *
     * @param string|null $ziel ziel
     *
     * @return self
     */
    public function setZiel($ziel)
    {
        if (is_null($ziel)) {
            throw new \InvalidArgumentException('non-nullable ziel cannot be null');
        }
        $this->container['ziel'] = $ziel;

        return $this;
    }

    /**
     * Gets inhalt
     *
     * @return string|null
     */
    public function getInhalt()
    {
        return $this->container['inhalt'];
    }

    /**
     * Sets inhalt
     *
     * @param string|null $inhalt inhalt
     *
     * @return self
     */
    public function setInhalt($inhalt)
    {
        if (is_null($inhalt)) {
            throw new \InvalidArgumentException('non-nullable inhalt cannot be null');
        }
        $this->container['inhalt'] = $inhalt;

        return $this;
    }

    /**
     * Gets methodik
     *
     * @return string|null
     */
    public function getMethodik()
    {
        return $this->container['methodik'];
    }

    /**
     * Sets methodik
     *
     * @param string|null $methodik methodik
     *
     * @return self
     */
    public function setMethodik($methodik)
    {
        if (is_null($methodik)) {
            throw new \InvalidArgumentException('non-nullable methodik cannot be null');
        }
        $this->container['methodik'] = $methodik;

        return $this;
    }

    /**
     * Gets hinweise
     *
     * @return string|null
     */
    public function getHinweise()
    {
        return $this->container['hinweise'];
    }

    /**
     * Sets hinweise
     *
     * @param string|null $hinweise hinweise
     *
     * @return self
     */
    public function setHinweise($hinweise)
    {
        if (is_null($hinweise)) {
            throw new \InvalidArgumentException('non-nullable hinweise cannot be null');
        }
        $this->container['hinweise'] = $hinweise;

        return $this;
    }

    /**
     * Gets sprache
     *
     * @return string|null
     */
    public function getSprache()
    {
        return $this->container['sprache'];
    }

    /**
     * Sets sprache
     *
     * @param string|null $sprache Die Sprache, in der die Veranstaltungsterminreihe durchgeführt wird.
     *
     * @return self
     */
    public function setSprache($sprache)
    {
        if (is_null($sprache)) {
            throw new \InvalidArgumentException('non-nullable sprache cannot be null');
        }
        $this->container['sprache'] = $sprache;

        return $this;
    }

    /**
     * Gets beginn_des_anmeldezeitraums
     *
     * @return \DateTime|null
     */
    public function getBeginnDesAnmeldezeitraums()
    {
        return $this->container['beginn_des_anmeldezeitraums'];
    }

    /**
     * Sets beginn_des_anmeldezeitraums
     *
     * @param \DateTime|null $beginn_des_anmeldezeitraums Das Datum, an dem der Anmeldezeitraum beginnt.
     *
     * @return self
     */
    public function setBeginnDesAnmeldezeitraums($beginn_des_anmeldezeitraums)
    {
        if (is_null($beginn_des_anmeldezeitraums)) {
            throw new \InvalidArgumentException('non-nullable beginn_des_anmeldezeitraums cannot be null');
        }
        $this->container['beginn_des_anmeldezeitraums'] = $beginn_des_anmeldezeitraums;

        return $this;
    }

    /**
     * Gets ende_des_anmeldezeitraums
     *
     * @return \DateTime|null
     */
    public function getEndeDesAnmeldezeitraums()
    {
        return $this->container['ende_des_anmeldezeitraums'];
    }

    /**
     * Sets ende_des_anmeldezeitraums
     *
     * @param \DateTime|null $ende_des_anmeldezeitraums Das Datum, an dem der Anmeldezeitraum endet.
     *
     * @return self
     */
    public function setEndeDesAnmeldezeitraums($ende_des_anmeldezeitraums)
    {
        if (is_null($ende_des_anmeldezeitraums)) {
            throw new \InvalidArgumentException('non-nullable ende_des_anmeldezeitraums cannot be null');
        }
        $this->container['ende_des_anmeldezeitraums'] = $ende_des_anmeldezeitraums;

        return $this;
    }

    /**
     * Gets veranstaltungsanbieter
     *
     * @return \Leifos\VedaConnector\GeneratedOpenApi\Model\Veranstaltungsanbieter|null
     */
    public function getVeranstaltungsanbieter()
    {
        return $this->container['veranstaltungsanbieter'];
    }

    /**
     * Sets veranstaltungsanbieter
     *
     * @param \Leifos\VedaConnector\GeneratedOpenApi\Model\Veranstaltungsanbieter|null $veranstaltungsanbieter veranstaltungsanbieter
     *
     * @return self
     */
    public function setVeranstaltungsanbieter($veranstaltungsanbieter)
    {
        if (is_null($veranstaltungsanbieter)) {
            throw new \InvalidArgumentException('non-nullable veranstaltungsanbieter cannot be null');
        }
        $this->container['veranstaltungsanbieter'] = $veranstaltungsanbieter;

        return $this;
    }

    /**
     * Gets veranstaltungsort
     *
     * @return \Leifos\VedaConnector\GeneratedOpenApi\Model\Veranstaltungsort|null
     */
    public function getVeranstaltungsort()
    {
        return $this->container['veranstaltungsort'];
    }

    /**
     * Sets veranstaltungsort
     *
     * @param \Leifos\VedaConnector\GeneratedOpenApi\Model\Veranstaltungsort|null $veranstaltungsort veranstaltungsort
     *
     * @return self
     */
    public function setVeranstaltungsort($veranstaltungsort)
    {
        if (is_null($veranstaltungsort)) {
            throw new \InvalidArgumentException('non-nullable veranstaltungsort cannot be null');
        }
        $this->container['veranstaltungsort'] = $veranstaltungsort;

        return $this;
    }

    /**
     * Gets zielgruppen
     *
     * @return \Leifos\VedaConnector\GeneratedOpenApi\Model\Zielgruppe[]|null
     */
    public function getZielgruppen()
    {
        return $this->container['zielgruppen'];
    }

    /**
     * Sets zielgruppen
     *
     * @param \Leifos\VedaConnector\GeneratedOpenApi\Model\Zielgruppe[]|null $zielgruppen Die Zielgruppen für die Veranstaltungsterminreihe.
     *
     * @return self
     */
    public function setZielgruppen($zielgruppen)
    {
        if (is_null($zielgruppen)) {
            throw new \InvalidArgumentException('non-nullable zielgruppen cannot be null');
        }
        $this->container['zielgruppen'] = $zielgruppen;

        return $this;
    }

    /**
     * Gets schlagwoerter
     *
     * @return \Leifos\VedaConnector\GeneratedOpenApi\Model\Schlagwort[]|null
     */
    public function getSchlagwoerter()
    {
        return $this->container['schlagwoerter'];
    }

    /**
     * Sets schlagwoerter
     *
     * @param \Leifos\VedaConnector\GeneratedOpenApi\Model\Schlagwort[]|null $schlagwoerter Die Schlagwörter für die Veranstaltungsterminreihe.
     *
     * @return self
     */
    public function setSchlagwoerter($schlagwoerter)
    {
        if (is_null($schlagwoerter)) {
            throw new \InvalidArgumentException('non-nullable schlagwoerter cannot be null');
        }
        $this->container['schlagwoerter'] = $schlagwoerter;

        return $this;
    }

    /**
     * Gets preis
     *
     * @return float|null
     */
    public function getPreis()
    {
        return $this->container['preis'];
    }

    /**
     * Sets preis
     *
     * @param float|null $preis Der Standardpreis der Veranstaltungsterminreihe.
     *
     * @return self
     */
    public function setPreis($preis)
    {
        if (is_null($preis)) {
            throw new \InvalidArgumentException('non-nullable preis cannot be null');
        }
        $this->container['preis'] = $preis;

        return $this;
    }

    /**
     * Gets preise_je_teilnehmergruppe
     *
     * @return \Leifos\VedaConnector\GeneratedOpenApi\Model\TeilnehmergruppePreis[]|null
     */
    public function getPreiseJeTeilnehmergruppe()
    {
        return $this->container['preise_je_teilnehmergruppe'];
    }

    /**
     * Sets preise_je_teilnehmergruppe
     *
     * @param \Leifos\VedaConnector\GeneratedOpenApi\Model\TeilnehmergruppePreis[]|null $preise_je_teilnehmergruppe Die Preise je nach Teilnehmergruppe der Veranstaltungsterminreihe.
     *
     * @return self
     */
    public function setPreiseJeTeilnehmergruppe($preise_je_teilnehmergruppe)
    {
        if (is_null($preise_je_teilnehmergruppe)) {
            throw new \InvalidArgumentException('non-nullable preise_je_teilnehmergruppe cannot be null');
        }
        $this->container['preise_je_teilnehmergruppe'] = $preise_je_teilnehmergruppe;

        return $this;
    }

    /**
     * Gets sachbearbeiter
     *
     * @return \Leifos\VedaConnector\GeneratedOpenApi\Model\Sachbearbeiter|null
     */
    public function getSachbearbeiter()
    {
        return $this->container['sachbearbeiter'];
    }

    /**
     * Sets sachbearbeiter
     *
     * @param \Leifos\VedaConnector\GeneratedOpenApi\Model\Sachbearbeiter|null $sachbearbeiter sachbearbeiter
     *
     * @return self
     */
    public function setSachbearbeiter($sachbearbeiter)
    {
        if (is_null($sachbearbeiter)) {
            throw new \InvalidArgumentException('non-nullable sachbearbeiter cannot be null');
        }
        $this->container['sachbearbeiter'] = $sachbearbeiter;

        return $this;
    }

    /**
     * Gets standardzahlungsbedingung
     *
     * @return \Leifos\VedaConnector\GeneratedOpenApi\Model\Zahlungsbedingung|null
     */
    public function getStandardzahlungsbedingung()
    {
        return $this->container['standardzahlungsbedingung'];
    }

    /**
     * Sets standardzahlungsbedingung
     *
     * @param \Leifos\VedaConnector\GeneratedOpenApi\Model\Zahlungsbedingung|null $standardzahlungsbedingung standardzahlungsbedingung
     *
     * @return self
     */
    public function setStandardzahlungsbedingung($standardzahlungsbedingung)
    {
        if (is_null($standardzahlungsbedingung)) {
            throw new \InvalidArgumentException('non-nullable standardzahlungsbedingung cannot be null');
        }
        $this->container['standardzahlungsbedingung'] = $standardzahlungsbedingung;

        return $this;
    }

    /**
     * Gets termine
     *
     * @return \Leifos\VedaConnector\GeneratedOpenApi\Model\VeranstaltungsterminDerReiheApiDto[]|null
     */
    public function getTermine()
    {
        return $this->container['termine'];
    }

    /**
     * Sets termine
     *
     * @param \Leifos\VedaConnector\GeneratedOpenApi\Model\VeranstaltungsterminDerReiheApiDto[]|null $termine Die einzelnen Termine der Reihe.
     *
     * @return self
     */
    public function setTermine($termine)
    {
        if (is_null($termine)) {
            throw new \InvalidArgumentException('non-nullable termine cannot be null');
        }
        $this->container['termine'] = $termine;

        return $this;
    }

    /**
     * Gets veranstaltungsform
     *
     * @return \Leifos\VedaConnector\GeneratedOpenApi\Model\Veranstaltungsform|null
     */
    public function getVeranstaltungsform()
    {
        return $this->container['veranstaltungsform'];
    }

    /**
     * Sets veranstaltungsform
     *
     * @param \Leifos\VedaConnector\GeneratedOpenApi\Model\Veranstaltungsform|null $veranstaltungsform veranstaltungsform
     *
     * @return self
     */
    public function setVeranstaltungsform($veranstaltungsform)
    {
        if (is_null($veranstaltungsform)) {
            throw new \InvalidArgumentException('non-nullable veranstaltungsform cannot be null');
        }
        $this->container['veranstaltungsform'] = $veranstaltungsform;

        return $this;
    }

    /**
     * Gets geschlossen
     *
     * @return bool|null
     */
    public function getGeschlossen()
    {
        return $this->container['geschlossen'];
    }

    /**
     * Sets geschlossen
     *
     * @param bool|null $geschlossen Gibt an, ob die Veranstaltungsterminreihe geschlossen ist.
     *
     * @return self
     */
    public function setGeschlossen($geschlossen)
    {
        if (is_null($geschlossen)) {
            throw new \InvalidArgumentException('non-nullable geschlossen cannot be null');
        }
        $this->container['geschlossen'] = $geschlossen;

        return $this;
    }

    /**
     * Gets fachlicher_ansprechpartner
     *
     * @return \Leifos\VedaConnector\GeneratedOpenApi\Model\Fachlicheransprechpartner|null
     */
    public function getFachlicherAnsprechpartner()
    {
        return $this->container['fachlicher_ansprechpartner'];
    }

    /**
     * Sets fachlicher_ansprechpartner
     *
     * @param \Leifos\VedaConnector\GeneratedOpenApi\Model\Fachlicheransprechpartner|null $fachlicher_ansprechpartner fachlicher_ansprechpartner
     *
     * @return self
     */
    public function setFachlicherAnsprechpartner($fachlicher_ansprechpartner)
    {
        if (is_null($fachlicher_ansprechpartner)) {
            throw new \InvalidArgumentException('non-nullable fachlicher_ansprechpartner cannot be null');
        }
        $this->container['fachlicher_ansprechpartner'] = $fachlicher_ansprechpartner;

        return $this;
    }

    /**
     * Gets veranstalter
     *
     * @return \Leifos\VedaConnector\GeneratedOpenApi\Model\Veranstalter|null
     */
    public function getVeranstalter()
    {
        return $this->container['veranstalter'];
    }

    /**
     * Sets veranstalter
     *
     * @param \Leifos\VedaConnector\GeneratedOpenApi\Model\Veranstalter|null $veranstalter veranstalter
     *
     * @return self
     */
    public function setVeranstalter($veranstalter)
    {
        if (is_null($veranstalter)) {
            throw new \InvalidArgumentException('non-nullable veranstalter cannot be null');
        }
        $this->container['veranstalter'] = $veranstalter;

        return $this;
    }

    /**
     * Gets zusatzinformationen
     *
     * @return string|null
     */
    public function getZusatzinformationen()
    {
        return $this->container['zusatzinformationen'];
    }

    /**
     * Sets zusatzinformationen
     *
     * @param string|null $zusatzinformationen Die Zusatzinformationen
     *
     * @return self
     */
    public function setZusatzinformationen($zusatzinformationen)
    {
        if (is_null($zusatzinformationen)) {
            throw new \InvalidArgumentException('non-nullable zusatzinformationen cannot be null');
        }
        $this->container['zusatzinformationen'] = $zusatzinformationen;

        return $this;
    }

    /**
     * Gets mitzubringen_durch_teilnehmer
     *
     * @return string|null
     */
    public function getMitzubringenDurchTeilnehmer()
    {
        return $this->container['mitzubringen_durch_teilnehmer'];
    }

    /**
     * Sets mitzubringen_durch_teilnehmer
     *
     * @param string|null $mitzubringen_durch_teilnehmer Mitzubringen durch Teilnehmer
     *
     * @return self
     */
    public function setMitzubringenDurchTeilnehmer($mitzubringen_durch_teilnehmer)
    {
        if (is_null($mitzubringen_durch_teilnehmer)) {
            throw new \InvalidArgumentException('non-nullable mitzubringen_durch_teilnehmer cannot be null');
        }
        $this->container['mitzubringen_durch_teilnehmer'] = $mitzubringen_durch_teilnehmer;

        return $this;
    }

    /**
     * Gets zielgruppen_details
     *
     * @return string|null
     */
    public function getZielgruppenDetails()
    {
        return $this->container['zielgruppen_details'];
    }

    /**
     * Sets zielgruppen_details
     *
     * @param string|null $zielgruppen_details Die Zielgruppen-Details
     *
     * @return self
     */
    public function setZielgruppenDetails($zielgruppen_details)
    {
        if (is_null($zielgruppen_details)) {
            throw new \InvalidArgumentException('non-nullable zielgruppen_details cannot be null');
        }
        $this->container['zielgruppen_details'] = $zielgruppen_details;

        return $this;
    }

    /**
     * Gets sachbearbeiter_tn
     *
     * @return \Leifos\VedaConnector\GeneratedOpenApi\Model\Sachbearbeiter|null
     */
    public function getSachbearbeiterTn()
    {
        return $this->container['sachbearbeiter_tn'];
    }

    /**
     * Sets sachbearbeiter_tn
     *
     * @param \Leifos\VedaConnector\GeneratedOpenApi\Model\Sachbearbeiter|null $sachbearbeiter_tn sachbearbeiter_tn
     *
     * @return self
     */
    public function setSachbearbeiterTn($sachbearbeiter_tn)
    {
        if (is_null($sachbearbeiter_tn)) {
            throw new \InvalidArgumentException('non-nullable sachbearbeiter_tn cannot be null');
        }
        $this->container['sachbearbeiter_tn'] = $sachbearbeiter_tn;

        return $this;
    }

    /**
     * Gets links
     *
     * @return \Leifos\VedaConnector\GeneratedOpenApi\Model\Link[]|null
     */
    public function getLinks()
    {
        return $this->container['links'];
    }

    /**
     * Sets links
     *
     * @param \Leifos\VedaConnector\GeneratedOpenApi\Model\Link[]|null $links links
     *
     * @return self
     */
    public function setLinks($links)
    {
        if (is_null($links)) {
            throw new \InvalidArgumentException('non-nullable links cannot be null');
        }
        $this->container['links'] = $links;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


